Repository openshift/oc-mirror, pull requests merged in 2021-09, with the labels that each got.

#66 fix(publish): changed overwrite option to true and comment cleanup
  pkg/archive/archive.go
  pkg/bundle/publish/publish.go
Labels: bug

#67 chore: workflow update
  .github/workflows/ci.yaml
  .goreleaser.yaml
Labels: automation

#73 Getting Started Docs
  README.md
  docs/createfull.md
  docs/imageset-config-ref.yaml
  docs/layout.md
  docs/overview.md
  docs/usage.md
Labels: documentation

#93 fix(publish): dedupe and correctly construct ICSP's for all image types
  README.md
  pkg/bundle/create/create.go
  pkg/bundle/publish/catalog_images.go
  pkg/bundle/publish/manifests.go
  pkg/bundle/publish/publish.go
  pkg/operator/mirror.go
Labels: bug

#98 fix(publish): do not return an error when no catalogs are present
  pkg/bundle/publish/catalog_images.go
  pkg/bundle/publish/manifests.go
Labels: bug

#97 fix(operators): prefer tags over digests when generating CatalogSources
  pkg/bundle/publish/manifests.go
Labels: bug
