Repository openshift/oc-mirror, pull requests merged in 2021-11, with the labels that each got.

#152 chore: docs update
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  docs/dev/getting-started.md
  docs/dev/styleguides.md
Labels: documentation, approved, lgtm

#150 feat(create, publish): backend config and remove podman
  Makefile
  go.mod
  go.sum
  pkg/bundle/create/create.go
  pkg/bundle/publish/catalog_images.go
  pkg/bundle/publish/catalog_images_test.go
  pkg/bundle/publish/manifests.go
  pkg/bundle/publish/publish.go
  pkg/config/v1alpha1/config_types.go
  pkg/config/v1alpha1/storage_config_types.go
  pkg/metadata/storage/git.go
  pkg/metadata/storage/local.go
  pkg/metadata/storage/registry.go
  pkg/metadata/storage/registry_test.go
  pkg/metadata/storage/storage.go
  pkg/metadata/store.go
  test/e2e-simple.sh
  test/operator/testdata/configs/latest/imageset-config-headsonly-backend.yaml
Labels: approved, lgtm

#142 feat: mirror2mirror capable UX
  Makefile
  README.md
  cmd/oc-bundle/create.go
  cmd/oc-bundle/main.go
  cmd/oc-bundle/publish.go
  cmd/oc-mirror/main.go
  pkg/additional/additional.go
  pkg/additional/additional_test.go
  pkg/additional/helm.go
  pkg/additional/helm_test.go
  pkg/bundle/create/create.go
  pkg/bundle/create/options.go
  pkg/bundle/files.go
  pkg/bundle/files_test.go
  pkg/bundle/image.go
  pkg/bundle/publish/options.go
  pkg/bundle/release_test.go
  pkg/cli/mirror/catalog_images.go
  pkg/cli/mirror/catalog_images_test.go
  pkg/cli/mirror/create.go
  pkg/cli/mirror/describe/describe.go
  pkg/cli/mirror/list/list.go
  pkg/cli/mirror/list/operators.go
  pkg/cli/mirror/list/releases.go
  pkg/cli/mirror/list/updates.go
  pkg/cli/mirror/manifests.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/publish.go
  pkg/cli/mirror/publish_test.go
  pkg/cli/mirror/version/version.go
  pkg/cli/options.go
  pkg/operator/mirror.go
  pkg/release/cincinnati.go
  pkg/release/cincinnati_test.go
  pkg/release/release.go
  pkg/release/release_test.go
  test/e2e-simple.sh
  test/lib.sh
Labels: approved, lgtm

#156 added jananir-redhat to OWNERS/reviewers
  OWNERS
Labels: approved, lgtm

#157 Prow initial test
  Makefile
  test/e2e-prow.sh
  test/prow/lib.sh
  test/prow/setup-testdata.sh
Labels: approved, lgtm

#159 Rename overview to overview.md
  docs/design/overview.md
Labels: approved, lgtm

#160 refactor: change root options
  CONTRIBUTING.md
  README.md
  pkg/archive/doc.go
  pkg/bundle/doc.go
  pkg/cli/mirror/additional.go
  pkg/cli/mirror/additional_test.go
  pkg/cli/mirror/catalog_images.go
  pkg/cli/mirror/cincinnati.go
  pkg/cli/mirror/cincinnati_test.go
  pkg/cli/mirror/create.go
  pkg/cli/mirror/doc.go
  pkg/cli/mirror/helm.go
  pkg/cli/mirror/helm_test.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/operator.go
  pkg/cli/mirror/options.go
  pkg/cli/mirror/publish.go
  pkg/cli/mirror/release.go
  pkg/cli/options.go
  pkg/config/credentials.go
  pkg/metadata/doc.go
  pkg/release/release_test.go
Labels: approved, lgtm

#155 feat(publish): multi-arch catalog rebuilds
  README.md
  pkg/cli/mirror/catalog_images.go
  pkg/cli/mirror/catalog_images_test.go
  pkg/metadata/storage/registry.go
  test/lib.sh
Labels: approved, lgtm

#162 chore: add component to OWNERS file
  OWNERS
Labels: approved, lgtm

#153 feat(publish): add registry as default backend for publishing
  pkg/cli/mirror/create.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/publish.go
  pkg/cli/mirror/publish_test.go
  pkg/cli/options.go
Labels: approved, lgtm, tide/merge-method-squash

#161 UX implementation for list releases, operators, and describe
  README.md
  pkg/bundle/files.go
  pkg/cincinnati/cincinnati.go
  pkg/cincinnati/cincinnati_test.go
  pkg/cli/mirror/describe/describe.go
  pkg/cli/mirror/list/operators.go
  pkg/cli/mirror/list/releases.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/publish.go
  pkg/cli/mirror/release.go
Labels: kind/feature, approved, lgtm

#163 docs: README and examples update
  README.md
  pkg/cli/mirror/list/list.go
  pkg/cli/mirror/list/operators.go
Labels: documentation, approved, lgtm

#164 feat(mirror): add --skip-missing and --continue-on-error
  pkg/cli/mirror/operator.go
  pkg/cli/mirror/operator_test.go
  pkg/cli/mirror/options.go
Labels: kind/feature, approved, lgtm

#167 Cleaned up Dockerfile
  Dockerfile
  rootfs/entrypoint.sh
Labels: ok-to-test, approved, lgtm

#165 fix(operator): only add OPM image when needed
  pkg/cli/mirror/create.go
  pkg/cli/mirror/create_test.go
Labels: kind/bug, approved, lgtm

#166 feat: add process release upgrades with cincinnati
  README.md
  pkg/bundle/files.go
  pkg/cincinnati/cincinnati.go
  pkg/cincinnati/cincinnati_test.go
  pkg/cincinnati/find.go
  pkg/cincinnati/find_test.go
  pkg/cli/mirror/create.go
  pkg/cli/mirror/list/updates.go
  pkg/cli/mirror/publish.go
  pkg/cli/mirror/publish_test.go
  pkg/cli/mirror/release.go
  pkg/config/v1alpha1/config_types.go
  pkg/metadata/storage/storage.go
Labels: kind/feature, approved, lgtm

#176 fix: add defer for file in get mapping and fix errors.As usage
  pkg/cli/mirror/release.go
  pkg/image/association.go
Labels: approved, lgtm

#177 fix: add target channel as channel on new runs
  pkg/cincinnati/cincinnati.go
  pkg/cincinnati/cincinnati_test.go
  pkg/cli/mirror/release.go
Labels: approved, lgtm

#173 chore(operator): remove unimplemented alternatives to `OperatorMetadata.ImagePin`
  pkg/cli/mirror/operator.go
  pkg/config/v1alpha1/metadata_types.go
  pkg/metadata/store.go
Labels: approved, lgtm

#181 chore: update organization and repo for go module
  README.md
  cmd/oc-mirror/main.go
  data/.metadata.json
  data/imageset-config.yaml
  docs/imageset-config-ref.yaml
  go.mod
  pkg/archive/archive.go
  pkg/archive/archive_test.go
  pkg/bundle/files.go
  pkg/bundle/files_test.go
  pkg/bundle/image.go
  pkg/bundle/image_test.go
  pkg/bundle/init.go
  pkg/cincinnati/find.go
  pkg/cincinnati/find_test.go
  pkg/cli/mirror/additional.go
  pkg/cli/mirror/additional_test.go
  pkg/cli/mirror/create.go
  pkg/cli/mirror/create_test.go
  pkg/cli/mirror/describe/describe.go
  pkg/cli/mirror/helm.go
  pkg/cli/mirror/helm_test.go
  pkg/cli/mirror/list/list.go
  pkg/cli/mirror/list/operators.go
  pkg/cli/mirror/list/releases.go
  pkg/cli/mirror/list/updates.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/operator.go
  pkg/cli/mirror/options.go
  pkg/cli/mirror/publish.go
  pkg/cli/mirror/publish_test.go
  pkg/cli/mirror/release.go
  pkg/cli/mirror/version/version.go
  pkg/config/load.go
  pkg/metadata/storage/foo/src/publish/.metadata.json
  pkg/metadata/storage/local.go
  pkg/metadata/storage/local_test.go
  pkg/metadata/storage/registry.go
  pkg/metadata/storage/registry_test.go
  pkg/metadata/storage/storage.go
  pkg/metadata/store.go
Labels: approved, lgtm, tide/merge-method-squash

#184 Add asciinema demo
  README.md
Labels: approved, kind/documentation, lgtm

#182 chore: docs/usage update
  README.md
  docs/usage.md
Labels: approved, lgtm

#148 feat(operator): use newer catalog differ to prune content by omission
  go.mod
  go.sum
  pkg/cli/mirror/operator.go
  pkg/config/v1alpha1/config_types.go
Labels: kind/feature, approved, lgtm

#195 fix: add metadata file to gitignore
  .gitignore
  pkg/metadata/storage/foo/src/publish/.metadata.json
Labels: approved, lgtm

#201 Switch example comment syntax to be yaml compliant without removing the comments. Ignore local copy of config file
  .gitignore
  docs/imageset-config-ref.yaml
Labels: ok-to-test, approved, lgtm

#202 chore: add examples dir
  README.md
  docs/examples/imageset-config-catalog-headsonly.yaml
  docs/examples/imageset-config-filter-catalog.yaml
  docs/examples/imageset-config-helm.yaml
  docs/examples/imageset-config-okd.yaml
  docs/examples/imageset-config-registry-backend.yaml
  docs/examples/imageset-config-release.yaml
Labels: approved, lgtm

#205 fix: change solution checking for image metadata existence
  pkg/metadata/storage/registry.go
Labels: approved

#203 feat(publish): Allow user to specify top-level namespace in target registry
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/options.go
  pkg/cli/mirror/publish.go
Labels: approved, lgtm
