Repository openshift/oc-mirror, pull requests merged in 2021-12, with the labels that each got.

#207 prow test framework
  test/e2e-prow.sh
  test/prow/builds/base/Dockerfile
  test/prow/builds/base/build.sh
  test/prow/builds/registry/.gitignore
  test/prow/builds/registry/Dockerfile
  test/prow/builds/registry/build.sh
  test/prow/builds/registry/config.yml
  test/prow/configs/imageset-helm.yaml
  test/prow/configs/imageset-image.yaml
  test/prow/configs/imageset-operator.yaml
  test/prow/lib.sh
  test/prow/setup-testdata.sh
  test/prow/test-helm.sh
  test/prow/test-operator-catalog.sh
  test/prow/test-simple-image.sh
Labels: approved, lgtm

#192 refactor(storage): local storage config refactor
  .gitignore
  README.md
  docs/usage.md
  pkg/archive/archive.go
  pkg/archive/archive_test.go
  pkg/cli/mirror/create.go
  pkg/cli/mirror/list/updates.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/options.go
  pkg/cli/mirror/publish.go
  pkg/cli/mirror/publish_test.go
  pkg/cli/options.go
  pkg/config/v1alpha1/metadata_types.go
  pkg/config/v1alpha1/storage_config_types.go
  pkg/metadata/storage/local.go
  pkg/metadata/storage/local_test.go
  pkg/metadata/storage/registry.go
  pkg/metadata/storage/registry_test.go
  pkg/metadata/storage/storage.go
  pkg/metadata/storage/storage_test.go
  test/e2e-simple.sh
  test/operator/setup-testdata.sh
  test/operator/testdata/configs/latest/imageset-config-headsonly-backend-registry.yaml
  test/operator/testdata/configs/latest/imageset-config-headsonly.yaml
Labels: approved, lgtm

#186 refactor(releases): refactor GetReleases for easier unit testing
  pkg/cincinnati/cincinnati.go
  pkg/cincinnati/cincinnati_test.go
  pkg/cincinnati/find.go
  pkg/cincinnati/find_test.go
  pkg/cli/mirror/list/updates.go
  pkg/cli/mirror/release.go
  pkg/cli/mirror/release_test.go
Labels: approved, lgtm

#208 fix: fix logic for returning ErrMetadataNotExist for registry backend
  docs/imageset-config-ref.yaml
  pkg/cli/mirror/options.go
  pkg/metadata/storage/registry.go
  pkg/metadata/storage/registry_test.go
Labels: approved, lgtm

#212 feat: adding permissions check before publishing to disconnected reg
  pkg/cincinnati/cincinnati_test.go
  pkg/cli/mirror/catalog_images.go
  pkg/cli/mirror/catalog_images_test.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/publish_test.go
  pkg/cli/mirror/release_test.go
  pkg/metadata/storage/registry_test.go
  pkg/metadata/storage/storage_test.go
Labels: approved, lgtm

#215 fix: set latest as the default if no tag or id is provided on addi…
  pkg/cli/mirror/additional.go
  pkg/cli/mirror/additional_test.go
Labels: approved, lgtm, tide/merge-method-squash

#211 fix(config): cleaned up config keys, made naming and defaults more intuitive
  docs/examples/imageset-config-filter-catalog.yaml
  docs/imageset-config-ref.yaml
  go.mod
  pkg/cli/mirror/list/updates.go
  pkg/cli/mirror/operator.go
  pkg/config/v1alpha1/config_test.go
  pkg/config/v1alpha1/config_types.go
  pkg/config/v1alpha1/include_config.go
  pkg/config/v1alpha1/testdata/config/valid.yaml
  pkg/metadata/storage/local_test.go
  pkg/metadata/storage/registry_test.go
  test/operator/testdata/configs/latest/imageset-config-full.yaml
  test/operator/testdata/configs/latest/imageset-config-headsonly-backend-registry.yaml
  test/operator/testdata/configs/latest/imageset-config-headsonly.yaml
Labels: approved, lgtm

#224 fix(mirror): add arg parse tests and create output dir for user
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/mirror_test.go
Labels: kind/bug, approved, lgtm

#223 fix: add namespace to check push permissions ref
  pkg/cli/mirror/list/operators_test.go
  pkg/cli/mirror/list/releases_test.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/mirror_test.go
Labels: approved, lgtm

#226 Prow PR fix
  Makefile
  test/e2e-prow.sh
  test/prow/lib.sh
  test/prow/test-operator-catalog.sh
  test/prow/test-simple-image.sh
Labels: approved, lgtm

#220 fix(catalogs): custom namespace catalog build fail
  docs/usage.md
  pkg/cli/mirror/catalog_images.go
  pkg/cli/mirror/catalog_images_test.go
  pkg/cli/mirror/manifests.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/publish.go
  test/e2e-simple.sh
Labels: approved, lgtm

#229 chore: temp e2e solution
  hack/e2e.sh
  test/e2e-config.yaml
  test/e2e-simple.sh
  test/lib.sh
  test/operator/setup-testdata.sh
  test/operator/testdata/configs/latest/imageset-config-full.yaml
  test/operator/testdata/configs/latest/imageset-config-headsonly-backend-registry.yaml
  test/operator/testdata/configs/latest/imageset-config-headsonly.yaml
  test/operator/testdata/indices/diff/index/index.yaml
  test/operator/testdata/indices/latest/index/index.yaml
Labels: approved, lgtm

#230 tidy before end to end
  Makefile
Labels: approved

#231 Revert "tidy before end to end"
  Makefile
Labels: approved

#233 chore: add mod flag to go install for crane
  Makefile
  test/lib.sh
Labels: approved

#234 chore: complete crane install in temp dir and turn off vendor mode
  test/lib.sh
Labels: approved

#232 fix: remove extra field on helm example config
  docs/examples/imageset-config-helm.yaml
Labels: approved, lgtm

#237 refactor(publish): add an ICSP generation struct to pass more inform…
  pkg/cli/mirror/manifests.go
  pkg/cli/mirror/manifests_test.go
  pkg/cli/mirror/publish.go
Labels: approved, lgtm

#244 feat: change operator config schema to support skipping dependencies
  pkg/cli/mirror/operator.go
  pkg/config/v1alpha1/config_types.go
  test/e2e-simple.sh
  test/operator/testdata/configs/latest/imageset-config-skip-deps.yaml
Labels: approved, lgtm

#238 chore: update operator registry dep
  OWNERS
  go.mod
  go.sum
  pkg/cli/mirror/catalog_images.go
  pkg/cli/mirror/operator.go
  pkg/config/v1alpha1/config_test.go
  pkg/config/v1alpha1/include_config.go
  test/lib.sh
Labels: approved, lgtm

#243 fix(operator): remove the old ref for include config diffs
  pkg/bundle/files.go
  pkg/bundle/files_test.go
  pkg/cli/mirror/create.go
  pkg/cli/mirror/operator.go
  pkg/cli/mirror/publish.go
  test/e2e-simple.sh
  test/lib.sh
  test/operator/testdata/configs/latest/imageset-config-filter-multi.yaml
  test/operator/testdata/configs/latest/imageset-config-filter.yaml
  test/start-docker-registry.sh
  test/stop-docker-registry.sh
  test/testcases.sh
Labels: approved, lgtm

#250 fix: add bundle name checking back to end to end and fix bundle names…
  pkg/cli/mirror/helm_test.go
  test/helm/setup-testdata.sh
  test/helm/testdata/charts/podinfo-6.0.0.tgz
  test/helm/testdata/configs/imageset-config-helm.yaml
  test/lib.sh
  test/testcases.sh
Labels: approved, lgtm

#251 fix(operator): produce error when invalid packages are provided with …
  docs/imageset-config-ref.yaml
  pkg/cli/mirror/operator.go
  pkg/cli/mirror/operator_test.go
Labels: approved, lgtm

#222 refactor(create): allow dry run option to run without failing
  pkg/cli/mirror/additional.go
  pkg/cli/mirror/create.go
  pkg/cli/mirror/create_test.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/mirror_test.go
  pkg/cli/mirror/operator.go
  pkg/cli/mirror/options.go
  pkg/cli/mirror/release.go
  pkg/cli/mirror/testdata/configs/test.yaml
Labels: approved, lgtm
