Repository openshift/oc-mirror, pull requests merged in 2022-03, with the labels that each got.

#341 fix: changes Catalog Source API version to v1alpha1
  pkg/cli/mirror/manifests.go
Labels: kind/bug, approved, lgtm

#336 refactor(release): adds a Client interface for Cincinnati client types
  pkg/archive/archive.go
  pkg/cincinnati/cincinnati.go
  pkg/cincinnati/cincinnati_test.go
  pkg/cincinnati/client.go
  pkg/cincinnati/find.go
  pkg/cincinnati/find_test.go
  pkg/cli/mirror/list/releases.go
  pkg/cli/mirror/list/updates.go
  pkg/cli/mirror/pack.go
  pkg/cli/mirror/release.go
  pkg/cli/mirror/release_test.go
  pkg/config/credentials.go
  pkg/image/mapping.go
  pkg/image/resolve.go
  pkg/metadata/storage/local.go
Labels: approved, lgtm

#343 fix: moves release images to a separate repo from release image content
  pkg/cli/mirror/release.go
Labels: approved, lgtm

#340 feat(releases): adds headsOnly flag to release to toggle full channel…
  README.md
  docs/examples/imageset-config-release-full-channel.yaml
  docs/examples/imageset-config-release-latest.yaml
  docs/examples/imageset-config-release.yaml
  pkg/cincinnati/cincinnati.go
  pkg/cincinnati/cincinnati_test.go
  pkg/cli/mirror/list/updates.go
  pkg/cli/mirror/release.go
  pkg/config/v1alpha2/config_types.go
  pkg/config/validate.go
  pkg/config/validate_test.go
Labels: approved, lgtm

#353 Docs/community meeting
  README.md
Labels: approved, kind/documentation, lgtm

#355 Ci/add ci targets
  Makefile
  test/integration/Makefile
Labels: approved, lgtm

#358 Enable CI rehearsals to hit the target
  Makefile
  test/integration/Makefile
Labels: approved, lgtm

#334 Bug 2058267: Add clarifying information to oc-mirror version command and remove alpha.3 from semver
  Makefile
  go.mod
  pkg/cli/mirror/version/version.go
  pkg/cli/mirror/version/version_test.go
  vendor/modules.txt
Labels: bugzilla/severity-medium, bugzilla/valid-bug, backport-risk-assessed, approved, cherry-pick-approved, qe-approved, lgtm

#342 feat(image): adds method to create Associations from remote sources
  go.mod
  pkg/bundle/image.go
  pkg/bundle/image_test.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/operator.go
  pkg/cli/mirror/publish.go
  pkg/cli/mirror/release.go
  pkg/image/association.go
  pkg/image/association_builder.go
  pkg/image/association_builder_test.go
  pkg/image/association_test.go
  pkg/image/credentials.go
  vendor/modules.txt
Labels: kind/feature, approved, lgtm

#363 fix: checks for error during declarative config diff before verifying…
  pkg/cli/mirror/operator.go
Labels: approved, lgtm

#345 Bug 2060837: resolves multiple channel heads in merged catalogs
  pkg/operator/merge.go
  pkg/operator/merge_test.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#333 refactor(catalog): replaces opm base image for catalog images with th…
  pkg/cli/mirror/catalog_images.go
  pkg/cli/mirror/catalog_images_test.go
  pkg/cli/mirror/create.go
  pkg/cli/mirror/create_test.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/operator.go
  pkg/cli/mirror/publish.go
  pkg/cli/mirror/util.go
  pkg/image/builder/image_builder.go
  pkg/image/builder/image_builder_test.go
  test/lib.sh
Labels: approved, lgtm

#374 Added git to Dockerfile
  Dockerfile
Labels: approved, lgtm

#360 Bug 2063955: fix(mirror): adds back continue-on-error use for missing images
  pkg/cli/mirror/additional.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/options.go
  pkg/image/association_builder.go
  pkg/image/association_builder_test.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#348 feat(releases): adds ShortestPath key to ReleaseChannel spec to toggl…
  docs/examples/imageset-config-release-full-channel.yaml
  docs/examples/imageset-config-release.yaml
  pkg/cincinnati/cincinnati.go
  pkg/cincinnati/cincinnati_test.go
  pkg/cli/mirror/release.go
  pkg/cli/mirror/release_test.go
  pkg/config/v1alpha2/config_types.go
  pkg/config/validate.go
  pkg/config/validate_test.go
Labels: kind/feature, approved, lgtm

#379 Added some extra output to help with CI rehearsals
  Makefile
  test/integration/Makefile
Labels: approved, lgtm

#362 [CI] Update CI targets for use
  .gitignore
  images/tests/Dockerfile.integration
  test/integration/Makefile
  test/integration/ansible.cfg
  test/integration/hosts
  test/integration/requirements.yml
  test/integration/scripts/build-image.sh
  test/integration/scripts/ci-mock.sh
  test/integration/scripts/ci-prereqs.sh
  test/integration/scripts/common.sh
  test/integration/scripts/connect.sh
  test/integration/scripts/post-run.sh
  test/integration/scripts/pre-run.sh
  test/integration/scripts/run.sh
  test/integration/vars.yml
Labels: approved, lgtm

#386 Added HOME for CI
  test/integration/scripts/common.sh
Labels: approved, lgtm

#357 Creating the release signature configmap for use during upgrades #125
  pkg/archive/archive.go
  pkg/bundle/init.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/publish.go
  pkg/cli/mirror/release-configmap.yaml
  pkg/cli/mirror/release.go
  pkg/config/metadata.go
Labels: ok-to-test, approved, lgtm

#364 feat(metadata): adds Associations to Metadata spec
  pkg/archive/archive.go
  pkg/archive/archive_test.go
  pkg/bundle/files.go
  pkg/bundle/files_test.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/options.go
  pkg/cli/mirror/pack.go
  pkg/cli/mirror/pack_test.go
  pkg/cli/mirror/publish.go
  pkg/cli/mirror/publish_test.go
  pkg/cli/mirror/testdata/artifacts/testbundle_seq2.tar
  pkg/cli/mirror/testdata/artifacts/testbundle_seq3.tar
  pkg/cli/mirror/testdata/configs/one.json
  pkg/cli/mirror/testdata/configs/three.json
  pkg/cli/mirror/testdata/configs/two.json
  pkg/config/v1alpha2/metadata_types.go
  pkg/config/v1alpha2/testdata/metadata/valid.json
  pkg/image/association.go
  pkg/image/convert.go
  pkg/image/convert_test.go
  pkg/metadata/store.go
Labels: approved, lgtm

#383 Bug 2069307: bump operator-registry dep v1.21.1
  go.mod
  go.sum
  vendor/github.com/operator-framework/api/pkg/constraints/constraint.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/csv.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/good_practices.go
  vendor/github.com/operator-framework/operator-registry/alpha/action/diff.go
  vendor/github.com/operator-framework/operator-registry/alpha/action/testdata/foo-index-v0.2.0-declcfg/foo/index.yaml
  vendor/github.com/operator-framework/operator-registry/alpha/declcfg/declcfg.go
  vendor/github.com/operator-framework/operator-registry/alpha/declcfg/diff.go
  vendor/github.com/operator-framework/operator-registry/pkg/containertools/runner.go
  vendor/github.com/operator-framework/operator-registry/pkg/image/containerdregistry/resolver.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/registry_to_model.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/types.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/load.go
  vendor/modules.txt
Labels: bugzilla/valid-bug, bugzilla/severity-urgent, approved, lgtm

#394 Fix component name for oc-mirror
  OWNERS
Labels: approved, lgtm
