Repository openshift/oc-mirror, pull requests merged in 2022-04, with the labels that each got.

#385 fix: adds context around sequence errors returned during publishing
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/publish.go
Labels: approved, lgtm

#381 feat: adds a custom user agent to registry context used by oc-mirror …
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/operator.go
  pkg/cli/mirror/publish.go
  pkg/cli/mirror/release.go
  pkg/image/association_builder.go
  pkg/image/association_builder_test.go
  pkg/image/credentials.go
  pkg/image/credentials_test.go
Labels: approved, lgtm

#401 fix: changes ConvertToAssociationSet methods to allow for duplicate c…
  pkg/image/convert.go
  pkg/image/convert_test.go
Labels: approved, lgtm

#405 Correct testdata publishing
  test/operator/bundles/bar/bar-bundle-v1.0.0/metadata/annotations.yaml
  test/operator/bundles/foo/foo-bundle-v0.2.0/metadata/annotations.yaml
  test/operator/bundles/foo/foo-bundle-v0.3.1/metadata/dependencies.yaml
  test/operator/publish_images.py
Labels: approved, lgtm

#387 refactor: heads only workflow to remove the requirement to merge FBCs
  pkg/api/v1alpha2/types_include_config.go
  pkg/api/v1alpha2/types_include_config_test.go
  pkg/api/v1alpha2/types_metadata.go
  pkg/cli/mirror/catalog_images.go
  pkg/cli/mirror/create.go
  pkg/cli/mirror/create_test.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/operator.go
  pkg/cli/mirror/pack.go
  pkg/cli/mirror/pack_test.go
  pkg/cli/mirror/release.go
  pkg/config/metadata.go
  pkg/image/association_set.go
  pkg/image/mapping.go
  pkg/metadata/store.go
  pkg/metadata/store_test.go
  pkg/metadata/testdata/catalogs/test.registry/catalog/sha256:30c794a11b4c340c77238c5b7ca845752904bd8b74b73a9b16d31253234da031/index/index.yaml
  pkg/operator/catalog_dir.go
  pkg/operator/catalog_dir_test.go
  pkg/operator/declcfg_to_includecfg.go
  pkg/operator/declfg_to_includecfg_test.go
  test/testcases.sh
Labels: approved, lgtm

#400 test: e2e improvements and new fmt/vet checks in Makefile
  .gitignore
  Makefile
  pkg/bundle/init.go
  pkg/cli/mirror/manifests.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/publish.go
  pkg/cli/mirror/release.go
  pkg/image/credentials_test.go
  pkg/operator/declcfg_to_includecfg.go
  test/e2e/artifacts/podinfo-6.0.0.tgz
  test/e2e/configs/imageset-config-filter-multi.yaml
  test/e2e/configs/imageset-config-filter.yaml
  test/e2e/configs/imageset-config-full.yaml
  test/e2e/configs/imageset-config-headsonly-backend-registry.yaml
  test/e2e/configs/imageset-config-headsonly.yaml
  test/e2e/configs/imageset-config-helm.yaml
  test/e2e/configs/imageset-config-skip-deps.yaml
  test/e2e/e2e-config.yaml
  test/e2e/e2e-simple.sh
  test/e2e/lib/check.sh
  test/e2e/lib/util.sh
  test/e2e/lib/workflow.sh
  test/e2e/testcases.sh
  test/helm/setup-testdata.sh
  test/lib.sh
Labels: approved, lgtm

#406 fix: changes ConvertToAssociationSet methods to allow for shared chil…
  pkg/image/convert.go
  pkg/image/convert_test.go
Labels: approved, lgtm

#396 fix: adds default tags to digest references and image pinning to remo…
  pkg/bundle/image.go
  pkg/cli/mirror/additional.go
  pkg/cli/mirror/mirror.go
  pkg/image/association_builder.go
  pkg/image/association_builder_test.go
  pkg/image/mapping.go
  pkg/image/mapping_test.go
Labels: approved, lgtm

#398 [BUG] fix(image): modifies layer appending on OCI images to ensure layers h…
  pkg/image/builder/image_builder.go
Labels: approved, lgtm

#392 Update list behavior and options
  pkg/cli/mirror/list/operators.go
  pkg/cli/mirror/list/releases.go
  pkg/cli/mirror/list/releases_test.go
Labels: approved, lgtm

#411 Bug 2075050: fix: adds handling for channel with different prefixes in cincinnati.go
  .gitignore
  pkg/cincinnati/cincinnati.go
  pkg/cincinnati/cincinnati_test.go
Labels: bugzilla/severity-medium, bugzilla/valid-bug, approved, lgtm

#409 test: adds unit tests in mirror package for release.go and mirror.go
  pkg/api/v1alpha2/types_metadata.go
  pkg/api/v1alpha2/types_platform.go
  pkg/archive/archive_test.go
  pkg/cincinnati/cincinnati.go
  pkg/cincinnati/cincinnati_test.go
  pkg/cincinnati/client.go
  pkg/cincinnati/client_test.go
  pkg/cincinnati/find.go
  pkg/cli/mirror/list/releases.go
  pkg/cli/mirror/list/releases_test.go
  pkg/cli/mirror/list/updates.go
  pkg/cli/mirror/list/updates_test.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/mirror_test.go
  pkg/cli/mirror/options.go
  pkg/cli/mirror/release.go
  pkg/cli/mirror/release_test.go
Labels: approved, lgtm

#420 fix(makefile): Fix phony target names for tidy and cross-build tasks …
  Makefile
Labels: approved, lgtm

#422 refactor(ux): list updates ux and adds unit tests for describe command
  pkg/cli/mirror/describe/describe.go
  pkg/cli/mirror/describe/describe_test.go
  pkg/cli/mirror/list/list.go
  pkg/cli/mirror/list/updates.go
  pkg/cli/mirror/list/updates_test.go
Labels: approved, lgtm

#412 feat(mirror): adds a skip-metadata-check flag to mirror command
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/options.go
  pkg/cli/mirror/pack.go
  pkg/cli/mirror/publish.go
  pkg/cli/mirror/publish_test.go
  pkg/metadata/storage/registry.go
Labels: approved, lgtm

#410 feat: adds implementation for --manifest-only flags to mirror command
  pkg/bundle/files.go
  pkg/bundle/files_test.go
  pkg/bundle/testdata/artifacts/testbundle_seq2.tar
  pkg/cli/mirror/describe/describe.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/mirror_test.go
  pkg/image/convert.go
  pkg/image/convert_test.go
Labels: approved, lgtm

#425 fix(publish): adds back evaluation of current associations in publish.go
  pkg/cli/mirror/publish.go
  test/e2e/lib/check.sh
  test/e2e/lib/util.sh
  test/e2e/lib/workflow.sh
  test/e2e/testcases.sh
Labels: approved, lgtm

#428 docs: adds more details to use, description. and examples to oc-mirro…
  pkg/cli/mirror/describe/describe.go
  pkg/cli/mirror/list/updates.go
  pkg/cli/mirror/mirror.go
Labels: approved, lgtm

#431 fix(makefile): remove clean from all target in Makefile
  Makefile
Labels: approved, lgtm

#433 fix(associations): ensure that the correct error types are thrown whe…
  pkg/image/association_builder.go
  pkg/image/association_builder_test.go
Labels: approved, lgtm

#424 fix(mapping): removes DockerClientDefaults from ctlgRef
  pkg/cli/mirror/additional.go
  pkg/cli/mirror/catalog_images.go
  pkg/cli/mirror/operator.go
  pkg/image/association_builder.go
  pkg/image/builder/image_builder.go
  pkg/image/digest.go
  pkg/image/mapping.go
  pkg/image/mapping_test.go
  test/e2e/configs/imageset-config-full-digest.yaml
  test/e2e/lib/util.sh
  test/e2e/lib/workflow.sh
  test/e2e/testcases.sh
Labels: approved, lgtm

#429 refactor(prune): changes prune to use worker queue for concurrent deletions
  pkg/cli/mirror/prune.go
  pkg/cli/mirror/prune_test.go
  vendor/github.com/openshift/api/apps/v1/consts.go
  vendor/github.com/openshift/api/apps/v1/deprecated_consts.go
  vendor/github.com/openshift/api/apps/v1/doc.go
  vendor/github.com/openshift/api/apps/v1/generated.pb.go
  vendor/github.com/openshift/api/apps/v1/generated.proto
  vendor/github.com/openshift/api/apps/v1/legacy.go
  vendor/github.com/openshift/api/apps/v1/register.go
  vendor/github.com/openshift/api/apps/v1/types.go
  vendor/github.com/openshift/api/apps/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/apps/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/build/v1/consts.go
  vendor/github.com/openshift/api/build/v1/doc.go
  vendor/github.com/openshift/api/build/v1/generated.pb.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/legacy.go
  vendor/github.com/openshift/api/build/v1/register.go
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/build/buildutil/buildutil.go
  vendor/github.com/openshift/library-go/pkg/image/imageutil/helpers.go
  vendor/github.com/openshift/library-go/pkg/network/networkutils/networkutils.go
  vendor/github.com/openshift/oc/pkg/cli/admin/prune/imageprune/OWNERS
  vendor/github.com/openshift/oc/pkg/cli/admin/prune/imageprune/doc.go
  vendor/github.com/openshift/oc/pkg/cli/admin/prune/imageprune/helper.go
  vendor/github.com/openshift/oc/pkg/cli/admin/prune/imageprune/prune.go
  vendor/modules.txt
Labels: approved, lgtm

#437 fix: modifies binary search algorithm to keep from a stack overflow
  pkg/operator/declcfg_to_includecfg.go
  pkg/operator/declfg_to_includecfg_test.go
Labels: approved, lgtm

#435 Improve error message for op list
  pkg/cli/mirror/list/operators.go
Labels: approved, lgtm

#432 feat(catalogs): add catalog target name and tag
  docs/examples/imageset-config-filter-catalog.yaml
  docs/imageset-config-ref.yaml
  go.mod
  pkg/api/v1alpha2/types_config.go
  pkg/cli/mirror/manifests.go
  pkg/cli/mirror/manifests_test.go
  pkg/cli/mirror/operator.go
  pkg/cli/mirror/release.go
  pkg/config/load_test.go
  pkg/config/validate.go
  pkg/config/validate_test.go
  pkg/metadata/store.go
  pkg/operator/merge.go
  pkg/operator/merge_test.go
  test/e2e/configs/imageset-config-headsonly-newtarget.yaml
  test/e2e/e2e-simple.sh
  test/e2e/lib/util.sh
  test/e2e/testcases.sh
Labels: kind/feature, approved, lgtm, kind/api-change

#436 feat(mirror): extends image blocking to allow the names to be specified as regular expressions
  docs/imageset-config-ref.yaml
  pkg/api/v1alpha2/types_platform.go
  pkg/archive/archive.go
  pkg/archive/doc.go
  pkg/bundle/image.go
  pkg/bundle/image_test.go
  pkg/bundle/workspace.go
  pkg/cincinnati/cincinnati.go
  pkg/cli/mirror/blocked.go
  pkg/cli/mirror/blocked_test.go
  pkg/cli/mirror/mirror.go
Labels: kind/feature, approved, lgtm

#440 fix: modifies release.go to remove and add release images to the mapping
  pkg/cli/mirror/release.go
Labels: approved, lgtm
