Repository openshift/oc-mirror, pull requests merged in 2022-10, with the labels that each got.

#514 updateURL: Allow overriding for CI builds
  pkg/cincinnati/cincinnati.go
  pkg/cincinnati/client.go
Labels: approved, lgtm

#495 Fix --ignore-hisotry description and some format adjustment
  docs/design/metadata-management.md
Labels: ok-to-test, approved, lgtm

#517 Pr 512 follow
  pkg/cli/mirror/copy.go
  pkg/cli/mirror/copy_test.go
  pkg/cli/mirror/mirror.go
Labels: approved, lgtm

#518 WRKLDS-468: Add registries.conf feature to mirror to alternative registry
  Dockerfile
  go.mod
  pkg/cli/mirror/copy.go
  pkg/cli/mirror/copy_test.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/options.go
  pkg/cli/mirror/testdata/configs/registries.conf
Labels: approved, lgtm

#520 remove afflom
  OWNERS
Labels: approved, lgtm

#519 WRKLDS-547
  pkg/cli/mirror/copy.go
  pkg/cli/mirror/copy_test.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/options.go
  pkg/cli/mirror/prune.go
  pkg/cli/mirror/testdata/artifacts/ibm-use-case/rhop-ctlg-oci-mashed/blobs/sha256/3986c6e039692ada9b5fa79ce51ce49bf6b24bc3af91d96e6c9d3d72f8077401
  pkg/cli/mirror/testdata/artifacts/ibm-use-case/rhop-ctlg-oci-mashed/blobs/sha256/c7c89df4a1f53d7e619080245c4784b6f5e6232fb71e98d981b89799ae578262
  pkg/cli/mirror/testdata/artifacts/ibm-use-case/rhop-ctlg-oci-mashed/blobs/sha256/cac5b2f40be10e552461651655ca8f3f6ba3f65f41ecf4345efbcf1875415db6
  pkg/cli/mirror/testdata/artifacts/ibm-use-case/rhop-ctlg-oci-mashed/index.json
  pkg/cli/mirror/testdata/artifacts/ibm-use-case/rhop-ctlg-oci-mashed/oci-layout
  pkg/cli/mirror/testdata/artifacts/ibm-use-case/rhop-ctlg-oci-mashed/olm_artifacts/configs/aws-load-balancer-operator/catalog.json
  pkg/cli/mirror/testdata/artifacts/ibm-use-case/rhop-ctlg-oci-mashed/olm_artifacts/configs/index.yaml
  pkg/cli/mirror/testdata/artifacts/ibm-use-case/rhop-ctlg-oci-mashed/olm_artifacts/configs/node-observability-operator/catalog.json
  pkg/cli/mirror/testdata/artifacts/olm_artifacts/configs/aws-load-balancer-operator/catalog.json
  pkg/cli/mirror/testdata/artifacts/olm_artifacts/configs/node-observability-operator/catalog.json
  pkg/cli/mirror/testdata/artifacts/olm_artifacts/fakecatalog/configs/aws-load-balancer-operator/catalog.json
  pkg/cli/mirror/testdata/artifacts/olm_artifacts/fakecatalog/configs/node-observability-operator/catalog.json
  pkg/cli/mirror/testdata/artifacts/olm_artifacts/rhop-ctlg-oci/configs/aws-load-balancer-operator/catalog.json
  pkg/cli/mirror/testdata/artifacts/olm_artifacts/rhop-ctlg-oci/configs/node-observability-operator/catalog.json
  pkg/cli/mirror/testdata/artifacts/rhop-ctlg-oci-mashed/blobs/sha256/3986c6e039692ada9b5fa79ce51ce49bf6b24bc3af91d96e6c9d3d72f8077401
  pkg/cli/mirror/testdata/artifacts/rhop-ctlg-oci-mashed/blobs/sha256/c7c89df4a1f53d7e619080245c4784b6f5e6232fb71e98d981b89799ae578262
  pkg/cli/mirror/testdata/artifacts/rhop-ctlg-oci-mashed/blobs/sha256/cac5b2f40be10e552461651655ca8f3f6ba3f65f41ecf4345efbcf1875415db6
  pkg/cli/mirror/testdata/artifacts/rhop-ctlg-oci-mashed/index.json
  pkg/cli/mirror/testdata/artifacts/rhop-ctlg-oci-mashed/oci-layout
  pkg/cli/mirror/testdata/artifacts/rhop-ctlg-oci-mashed/olm_artifacts/configs/aws-load-balancer-operator/catalog.json
  pkg/cli/mirror/testdata/artifacts/rhop-ctlg-oci-mashed/olm_artifacts/configs/node-observability-operator/catalog.json
  pkg/cli/mirror/testdata/artifacts/rhop-ctlg-oci/olm_artifacts/configs/aws-load-balancer-operator/catalog.json
  pkg/cli/mirror/testdata/artifacts/rhop-ctlg-oci/olm_artifacts/configs/node-observability-operator/catalog.json
  pkg/image/image.go
  pkg/operator/diff/internal/diff.go
  test/e2e/configs/imageset-config-oci-copy.yaml
  test/e2e/configs/imageset-config-oci-mirror.yaml
  test/e2e/e2e-simple.sh
  test/e2e/lib/util.sh
  test/e2e/lib/workflow.sh
  test/e2e/testcases.sh
Labels: approved, lgtm

#521 docs: adds grammar fixes to metadata-management.md
  docs/design/metadata-management.md
Labels: documentation, approved, lgtm
