Repository openshift/oc-mirror, pull requests merged in 2022-05, with the labels that each got.

#393 [CI] Correct CI Integration target
  docs/dev/getting-started.md
  test/integration/Makefile
  test/integration/ansible.cfg
  test/integration/hosts
  test/integration/hosts.yml
  test/integration/requirements.yml
  test/integration/scripts/build-image.sh
  test/integration/scripts/ci-mock.sh
  test/integration/scripts/ci-prereqs.sh
  test/integration/scripts/common.sh
  test/integration/scripts/connect.sh
  test/integration/scripts/post-run.sh
  test/integration/scripts/pre-run.sh
  test/integration/scripts/run.sh
  test/integration/vars.yml
Labels: approved, lgtm

#443 docs: cleanup and updates imageset-configuration.md
  docs/design/imageset-configuration.md
Labels: approved, kind/documentation, lgtm

#416 init workflow
  .gitignore
  README.md
  go.mod
  pkg/api/v1alpha2/types_config.go
  pkg/cli/mirror/initcmd/initcmd.go
  pkg/cli/mirror/initcmd/initcmd_test.go
  pkg/cli/mirror/list/operators.go
  pkg/cli/mirror/list/releases.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/testdata/v2/redhat/redhat-operator-index/tags/list
  pkg/cli/mirror/version/version.go
  pkg/image/image.go
  pkg/version/version.go
Labels: ok-to-test, approved, lgtm

#413 Bug 2075051: [release-4.10] fix: adds handling for channel with different prefixes in cincinnati.go
  pkg/cincinnati/cincinnati.go
  pkg/cincinnati/cincinnati_test.go
Labels: bugzilla/severity-medium, bugzilla/valid-bug, backport-risk-assessed, approved, cherry-pick-approved, lgtm

#448 [CI] Set integration test to use mirror_registry
  test/integration/requirements.yml
  test/integration/vars.yml
Labels: approved, lgtm

#450 docs: add notes about flag usage to usage.md
  docs/design/imageset-configuration.md
  docs/design/metadata-management.md
  docs/design/overview.md
  docs/design/workflows.md
  docs/usage.md
Labels: approved, lgtm

#451 feat(publish): adds mapping output after publishing operations
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/operator.go
  pkg/cli/mirror/util.go
Labels: approved, lgtm

#414 Replace logrus with klog
  cmd/oc-mirror/main.go
  go.mod
  go.sum
  pkg/archive/archive.go
  pkg/bundle/files.go
  pkg/bundle/workspace.go
  pkg/cincinnati/cincinnati.go
  pkg/cli/mirror/additional.go
  pkg/cli/mirror/catalog_images.go
  pkg/cli/mirror/create.go
  pkg/cli/mirror/create_test.go
  pkg/cli/mirror/helm.go
  pkg/cli/mirror/manifests.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/operator.go
  pkg/cli/mirror/options.go
  pkg/cli/mirror/pack.go
  pkg/cli/mirror/prune.go
  pkg/cli/mirror/publish.go
  pkg/cli/mirror/release.go
  pkg/cli/options.go
  pkg/image/mapping.go
  pkg/metadata/storage/local.go
  pkg/metadata/storage/registry.go
  pkg/metadata/storage/storage.go
  test/e2e/lib/util.sh
  vendor/github.com/go-logr/logr/.golangci.yaml
  vendor/github.com/go-logr/logr/CHANGELOG.md
  vendor/github.com/go-logr/logr/CONTRIBUTING.md
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/discard.go
  vendor/github.com/go-logr/logr/logr.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/exit.go
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/internal/buffer/buffer.go
  vendor/k8s.io/klog/v2/internal/clock/README.md
  vendor/k8s.io/klog/v2/internal/clock/clock.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/internal/severity/severity.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/klog/v2/klog_file_others.go
  vendor/k8s.io/klog/v2/klog_file_windows.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/modules.txt
Labels: approved, lgtm

#445 feat(release): expose architecture filter options for Platforms
  docs/examples/imageset-config-release-alt-arch.yaml
  docs/imageset-config-ref.yaml
  pkg/api/v1alpha2/types_config.go
  pkg/cli/mirror/list/releases.go
  pkg/cli/mirror/list/updates.go
  pkg/cli/mirror/list/updates_test.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/mirror_test.go
  pkg/cli/mirror/options.go
  pkg/cli/mirror/release.go
  pkg/config/defaults.go
  pkg/config/defaults_test.go
  pkg/config/load.go
  pkg/config/validate.go
  pkg/config/validate_test.go
Labels: kind/feature, approved, lgtm, kind/api-change

#444 fix(pruning): changes image planning for pruning operations to use the destination image repo
  pkg/cli/mirror/helm.go
  pkg/cli/mirror/prune.go
  pkg/cli/mirror/prune_test.go
  test/e2e/testcases.sh
Labels: approved, lgtm

#454 fix(ci) Update integration test collection to inherit bugfixes
  test/integration/requirements.yml
Labels: approved, lgtm

#438 feat: heads only packages
  go.mod
  go.sum
  pkg/api/v1alpha2/types_include_config.go
  pkg/cli/mirror/operator.go
  pkg/config/metadata.go
  pkg/metadata/store.go
  pkg/metadata/store_test.go
  pkg/metadata/testdata/catalogs/test.registry/catalog/sha256:30c794a11b4c340c77238c5b7ca845752904bd8b74b73a9b16d31253234da031/include-config.gob
  pkg/metadata/testdata/catalogs/test.registry/catalog/sha256:30c794a11b4c340c77238c5b7ca845752904bd8b74b73a9b16d31253234da031/index/index.yaml
  pkg/operator/declcfg_to_includecfg.go
  pkg/operator/declfg_to_includecfg_test.go
  test/e2e/configs/imageset-config-filter-multi-prune.yaml
  test/e2e/e2e-simple.sh
  test/e2e/testcases.sh
  vendor/github.com/operator-framework/operator-registry/alpha/action/diff.go
  vendor/github.com/operator-framework/operator-registry/alpha/declcfg/diff.go
  vendor/github.com/operator-framework/operator-registry/alpha/declcfg/diff_include.go
  vendor/modules.txt
Labels: approved, lgtm

#455 chore(logging): Adds logrus setup back and changes klog verbosity levels
  docs/usage.md
  go.mod
  pkg/archive/archive.go
  pkg/bundle/files.go
  pkg/cincinnati/cincinnati.go
  pkg/cli/log.go
  pkg/cli/mirror/catalog_images.go
  pkg/cli/mirror/cincinnati_graph_image.go
  pkg/cli/mirror/create.go
  pkg/cli/mirror/helm.go
  pkg/cli/mirror/manifests.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/operator.go
  pkg/cli/mirror/operator_test.go
  pkg/cli/mirror/pack.go
  pkg/cli/mirror/prune.go
  pkg/cli/mirror/publish.go
  pkg/cli/mirror/release.go
  pkg/cli/options.go
  pkg/image/builder/image_builder.go
  pkg/image/convert.go
  pkg/image/mapping.go
  pkg/metadata/storage/local.go
  pkg/metadata/storage/registry.go
  pkg/metadata/storage/storage.go
  pkg/metadata/store.go
Labels: approved, lgtm

#458 Bug 2086962: fix(publish): adds check for dry-run to ensure metadata is not proces…
  internal/testutils/testutils.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/publish.go
Labels: bugzilla/severity-medium, bugzilla/valid-bug, approved, lgtm

#467 Bug 2086964: fix(operators): adds better support for packages with multiple channel configurations
  pkg/operator/declcfg_to_includecfg.go
  pkg/operator/declfg_to_includecfg_test.go
Labels: bugzilla/severity-medium, bugzilla/valid-bug, approved, lgtm

#470 Bug 2088130: fix(init): bug/init cmd force prompting
  config.yaml
  docs/usage.md
  pkg/cli/mirror/initcmd/initcmd.go
  pkg/cli/mirror/initcmd/initcmd_test.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-low

#474 Bug 2087764: fix(operators): updates operator registry to 1.22.1 inherit fix for e…
  go.mod
  go.sum
  vendor/github.com/operator-framework/operator-registry/alpha/declcfg/diff.go
  vendor/modules.txt
Labels: bugzilla/severity-medium, bugzilla/valid-bug, approved, lgtm

#463 Bug 2086972: test: adds test cases to image builder and describe pkgs and add go sec fixes
  internal/testutils/testutils.go
  pkg/bundle/files.go
  pkg/cli/mirror/catalog_images.go
  pkg/cli/mirror/cincinnati_graph_image.go
  pkg/cli/mirror/create.go
  pkg/cli/mirror/describe/describe_test.go
  pkg/cli/mirror/describe/testdata/test_describe.tar
  pkg/cli/mirror/prune.go
  pkg/cli/mirror/release.go
  pkg/cli/options.go
  pkg/image/builder/image_builder.go
  pkg/image/builder/image_builder_test.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-low
