Repository openshift/oc-mirror, pull requests merged in 2022-06, with the labels that each got.

#464 Bug 2088634: fix(operator): adds validation after rendering dc to check for invali…
  docs/examples/imageset-config-catalog-headsonly.yaml
  docs/examples/imageset-config-filter-catalog.yaml
  pkg/cli/mirror/operator.go
  pkg/cli/mirror/operator_test.go
Labels: bugzilla/severity-medium, bugzilla/valid-bug, approved, lgtm

#469 Bug 2087024: fix(mapping): modifies mapping.txt for compat…
  pkg/cli/mirror/manifests.go
  pkg/cli/mirror/mirror.go
  pkg/image/mapping.go
  pkg/image/mapping_test.go
Labels: bugzilla/severity-medium, bugzilla/valid-bug, approved, lgtm

#482 Bug 2092887: Rename filter-options flag to filter-by-archs
  pkg/cli/mirror/list/releases.go
  pkg/cli/mirror/list/releases_test.go
Labels: bugzilla/severity-medium, bugzilla/valid-bug, approved, lgtm

#473 Bug 2087271: fix(mirror): adds sequence checks for mirror to mirror operations
  pkg/bundle/workspace.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/publish.go
  pkg/cli/mirror/publish_test.go
  pkg/cli/mirror/sequence.go
  pkg/cli/mirror/sequence_test.go
Labels: bugzilla/severity-medium, bugzilla/valid-bug, approved, lgtm

#477 Bug 2089396: pruning plan missing
  README.md
  config.yaml
  docs/usage.md
  pkg/cli/mirror/initcmd/initcmd.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/prune.go
  pkg/cli/mirror/prune_test.go
  pkg/cli/mirror/publish.go
Labels: bugzilla/severity-medium, bugzilla/valid-bug, approved, lgtm

#483 Bug 2092815: fix(pruning): allows continue-on-error to be used with pruning operat…
  docs/design/overview.md
  docs/usage.md
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/options.go
  pkg/cli/mirror/prune.go
  pkg/cli/mirror/prune_test.go
  pkg/cli/mirror/util.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#486 Bug 2094866: fix(pruning): handles child manifest deletion and tagged references
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/prune.go
  pkg/cli/mirror/prune_test.go
Labels: bugzilla/severity-medium, bugzilla/valid-bug, approved, lgtm

#487 Bug 2095347: removes extra results directories when mirroring disk to mirror
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/publish.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-low

#489 Bug 2098172: Adds validation for inaccessible registry endpoints
  pkg/cli/mirror/publish.go
  pkg/config/metadata.go
  pkg/metadata/storage/registry.go
  pkg/metadata/storage/registry_test.go
Labels: kind/bug, bugzilla/severity-medium, bugzilla/valid-bug, approved, lgtm

#490 Bug 2098610: fix(mirror): removes push permission check with manifest-only is used
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/mirror_test.go
Labels: bugzilla/severity-medium, bugzilla/valid-bug, approved, lgtm

#492 Bug 2099899: fix(publish): modifies layer fetcher to gather repos into a map and u…
  pkg/cli/mirror/publish.go
  pkg/cli/mirror/publish_test.go
  pkg/image/association_set.go
  pkg/image/association_set_test.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#485 bug 2093957: [docs] Light readme maint
  README.md
Labels: bugzilla/severity-medium, bugzilla/valid-bug, approved, lgtm
