Repository openshift/oc-mirror, pull requests merged in 2022-01, with the labels that each got.

#252 chore(testing): add unit test for image package and renamed some asso…
  pkg/cli/mirror/publish.go
  pkg/image/association.go
  pkg/image/association_test.go
  pkg/image/testdata/v2/index_manifest/manifests/latest
  pkg/image/testdata/v2/index_manifest/manifests/sha256:60f5921e0f6a21a485a0a4e9415761afb5b60814bbe8a6864cb12b90ae24c1d0
  pkg/image/testdata/v2/index_manifest/manifests/sha256:9574416689665a82cb4eaf43463da5b6156071ebbec117262eef7fa32b4d7021
  pkg/image/testdata/v2/index_manifest/manifests/sha256:b8a825862d73b2f1110dd9c5fc0631f47117c7cd99e42efa34244cd82bd6742f
  pkg/image/testdata/v2/index_manifest/manifests/sha256:bab3a6153010b614c8764548f0dbe34c4a7dce4ea278a94713c3e9a936bb74e6
  pkg/image/testdata/v2/index_manifest/manifests/sha256:d15a206e4ee462e82ab722ed84dfa514ab9ed8d85100d591c04314ae7c2162ee
  pkg/image/testdata/v2/single_manifest/manifests/latest
  pkg/image/testdata/v2/single_manifest/manifests/sha256:d31c6ea5c50be93d6eb94d2b508f0208e84a308c011c6454ebf291d48b37df19
  test/lib.sh
Labels: approved, lgtm

#235 fix(create): add metadata rollback for errors after metadata write in create operation
  pkg/cli/mirror/create.go
  pkg/cli/mirror/create_test.go
  pkg/cli/mirror/helm_test.go
  pkg/cli/mirror/options.go
  pkg/cli/mirror/publish_test.go
  pkg/cli/mirror/testdata/artifacts/podinfo-6.0.0.tgz
  pkg/cli/mirror/testdata/artifacts/podinfo.yaml
  pkg/cli/mirror/testdata/artifacts/testbundle_diff-uid.tar
  pkg/cli/mirror/testdata/artifacts/testbundle_seq1.tar
  pkg/cli/mirror/testdata/artifacts/testbundle_seq2.tar
  pkg/cli/mirror/testdata/artifacts/testbundle_seq3.tar
  pkg/cli/mirror/testdata/configs/diff-uid.json
  pkg/cli/mirror/testdata/configs/one.json
  pkg/cli/mirror/testdata/configs/test.yaml
  pkg/cli/mirror/testdata/configs/three.json
  pkg/cli/mirror/testdata/configs/two.json
  test/archiver/testdata/bar-bundle01.tar.gz
  test/archiver/testdata/bar-bundle02.tar.gz
  test/release/testdata/updategraph.json
Labels: approved, lgtm

#255 chore: change all unit test names to comply with Go convention
  pkg/archive/archive_test.go
  pkg/bundle/files_test.go
  pkg/bundle/image_test.go
  pkg/cincinnati/cincinnati_test.go
  pkg/cincinnati/find_test.go
  pkg/cli/mirror/additional_test.go
  pkg/cli/mirror/catalog_images_test.go
  pkg/cli/mirror/create_test.go
  pkg/cli/mirror/helm_test.go
  pkg/cli/mirror/manifests_test.go
  pkg/cli/mirror/publish_test.go
  pkg/cli/mirror/release_test.go
  pkg/image/association_test.go
  pkg/metadata/storage/local_test.go
  pkg/metadata/storage/registry_test.go
  pkg/metadata/storage/storage_test.go
Labels: approved, lgtm

#254 fix: adds validation for ImageSetConfiguration and add insecure to na…
  go.mod
  go.sum
  pkg/cli/mirror/catalog_images.go
  pkg/cli/mirror/catalog_images_test.go
  pkg/cli/mirror/create.go
  pkg/cli/mirror/list/releases.go
  pkg/cli/mirror/mirror.go
  pkg/config/load.go
  pkg/config/validate.go
  pkg/config/validate_test.go
  pkg/metadata/storage/registry.go
Labels: approved, lgtm

#256 Minor help text updates
  pkg/cli/mirror/describe/describe.go
  pkg/cli/mirror/list/list.go
  pkg/cli/mirror/list/operators.go
  pkg/cli/mirror/list/releases.go
  pkg/cli/mirror/mirror.go
Labels: approved, lgtm

#258 fix(mirror): change MirrorOptions to be passed by reference due to po…
  pkg/cli/mirror/additional.go
  pkg/cli/mirror/additional_test.go
  pkg/cli/mirror/create.go
  pkg/cli/mirror/helm.go
  pkg/cli/mirror/operator.go
  pkg/cli/mirror/operator_test.go
  pkg/cli/mirror/publish.go
  pkg/cli/mirror/release.go
Labels: approved, lgtm

#259 chore: spelling and grammar fixes in comments and docs
  docs/dev/getting-started.md
  pkg/bundle/files_test.go
  pkg/cincinnati/cincinnati_test.go
  pkg/cincinnati/find_test.go
  pkg/cli/mirror/create.go
  pkg/cli/mirror/helm.go
  pkg/cli/mirror/publish_test.go
  pkg/cli/mirror/release.go
  pkg/config/v1alpha1/metadata_types.go
  pkg/image/association.go
  pkg/metadata/storage/local.go
  pkg/metadata/store.go
Labels: approved, lgtm

#261 chore: update OWNERS file
  OWNERS
Labels: approved, lgtm

#260 refactor(bundle): simplify file reconciling functions and improve unit t…
  pkg/bundle/files.go
  pkg/bundle/files_test.go
  pkg/cli/mirror/create.go
  pkg/config/metadata.go
Labels: approved, lgtm

#257 chore: update API group name for Imageset types
  README.md
  docs/examples/imageset-config-catalog-headsonly.yaml
  docs/examples/imageset-config-filter-catalog.yaml
  docs/examples/imageset-config-helm.yaml
  docs/examples/imageset-config-okd.yaml
  docs/examples/imageset-config-registry-backend.yaml
  docs/examples/imageset-config-release.yaml
  docs/imageset-config-ref.yaml
  pkg/cli/mirror/testdata/artifacts/testbundle_diff-uid.tar
  pkg/cli/mirror/testdata/artifacts/testbundle_seq1.tar
  pkg/cli/mirror/testdata/artifacts/testbundle_seq2.tar
  pkg/cli/mirror/testdata/artifacts/testbundle_seq3.tar
  pkg/cli/mirror/testdata/configs/diff-uid.json
  pkg/cli/mirror/testdata/configs/one.json
  pkg/cli/mirror/testdata/configs/test.yaml
  pkg/cli/mirror/testdata/configs/three.json
  pkg/cli/mirror/testdata/configs/two.json
  pkg/config/v1alpha1/config_test.go
  pkg/config/v1alpha1/metadata_test.go
  pkg/config/v1alpha1/register.go
  pkg/config/v1alpha1/testdata/config/valid.yaml
  pkg/config/v1alpha1/testdata/metadata/valid.json
  test/helm/testdata/configs/imageset-config-helm.yaml
  test/operator/testdata/configs/latest/imageset-config-filter-multi.yaml
  test/operator/testdata/configs/latest/imageset-config-filter.yaml
  test/operator/testdata/configs/latest/imageset-config-full.yaml
  test/operator/testdata/configs/latest/imageset-config-headsonly-backend-registry.yaml
  test/operator/testdata/configs/latest/imageset-config-headsonly.yaml
  test/operator/testdata/configs/latest/imageset-config-skip-deps.yaml
  test/prow/configs/imageset-image.yaml
  test/prow/configs/imageset-operator.yaml
Labels: approved, lgtm

#263 fix(publish): add name options to fix catalog rebuild with HTTP regis…
  pkg/cli/mirror/catalog_images.go
  test/lib.sh
  test/testcases.sh
Labels: approved, lgtm

#266 Fix/clean build
  docs/dev/getting-started.md
  hack/build.sh
Labels: ok-to-test, approved, lgtm

#265 fix(publish): add appropriate media type on image index during catalog …
  go.mod
  go.sum
  pkg/cli/mirror/catalog_images.go
  pkg/cli/mirror/operator.go
  pkg/cli/mirror/publish.go
  pkg/image/association.go
  pkg/image/association_test.go
Labels: approved, lgtm

#267 chore: mark filter-by-os flag as hidden temporarily
  pkg/cli/mirror/additional.go
  pkg/cli/mirror/create.go
  pkg/cli/mirror/create_test.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/mirror_test.go
  pkg/cli/mirror/options.go
  pkg/cli/mirror/release.go
  pkg/cli/options.go
  pkg/metadata/storage/registry.go
Labels: approved, lgtm

#271 test: add unit tests for findBlobRepo function in publish.go
  pkg/cli/mirror/publish.go
  pkg/cli/mirror/publish_test.go
Labels: approved, lgtm

#268 feat: add support for podman credential location
  .gitignore
  README.md
  docs/usage.md
  go.mod
  go.sum
  pkg/cli/mirror/additional.go
  pkg/cli/mirror/operator.go
  pkg/cli/mirror/publish.go
  pkg/cli/mirror/release.go
  pkg/config/credentials.go
  pkg/config/v1alpha1/config_test.go
  pkg/config/v1alpha1/config_types.go
  pkg/config/v1alpha1/testdata/config/valid.yaml
  pkg/image/association.go
  pkg/metadata/store.go
Labels: approved, lgtm

#278 fix: adds ability to disable TLS uniformly throughout oc-mirror
  Makefile
  go.mod
  go.sum
  pkg/bundle/image.go
  pkg/cli/mirror/additional.go
  pkg/cli/mirror/additional_test.go
  pkg/cli/mirror/catalog_images.go
  pkg/cli/mirror/catalog_images_test.go
  pkg/cli/mirror/create.go
  pkg/cli/mirror/helm.go
  pkg/cli/mirror/list/updates.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/operator.go
  pkg/cli/mirror/options.go
  pkg/cli/mirror/publish.go
  pkg/cli/mirror/release.go
  pkg/metadata/store.go
  test/lib.sh
Labels: approved, lgtm

#281 chore(catalog): add merge functionality for file-based catalogs
  go.mod
  go.sum
  pkg/cli/mirror/catalog_images.go
  pkg/operator/doc.go
  pkg/operator/merge.go
  pkg/operator/merge_test.go
Labels: approved, lgtm

#280 fix(publish): implements ICSPTypes for processing and grouping per type
  pkg/archive/archive_test.go
  pkg/cli/mirror/manifests.go
  pkg/cli/mirror/manifests_test.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/operator.go
  pkg/cli/mirror/publish.go
  pkg/cli/mirror/release.go
  pkg/config/credentials.go
  pkg/config/v1alpha1/register.go
  pkg/image/association.go
Labels: approved, lgtm

#276 fix(storage): adds a pull permission check to respond to 401 errors
  go.sum
  pkg/cli/mirror/catalog_images.go
  pkg/metadata/storage/registry.go
Labels: approved, lgtm

#286 fix(storage): adds a pull permission check to respond to 401 errors (…
  go.sum
  pkg/cli/mirror/catalog_images.go
  pkg/metadata/storage/registry.go
Labels: approved, lgtm

#288 Documenting oc-mirror vs oc mirror [183]
  docs/usage.md
Labels: ok-to-test, approved, lgtm

#289 chore: add Dockerfile for CI builds
  images/cli/Dockerfile.ci
Labels: approved

#290 chore: add Dockerfile for CI builds (#289)
  images/cli/Dockerfile.ci
Labels: approved

#291 update branch
  docs/usage.md
  go.sum
  images/cli/Dockerfile.ci
  pkg/cli/mirror/catalog_images.go
  pkg/metadata/storage/registry.go
Labels: approved, lgtm

#297 chore: set mod flag to vendor on Makefile
  Makefile
Labels: approved, lgtm
