Repository openshift/oc-mirror, pull requests merged in 2023-01, with the labels that each got.

#548 New reviewers: Luigi Mario Zuccarelli, Sherine Khoury
  OWNERS
Labels: approved, lgtm

#547 OCPBUGS-5891: fix: adds logic that searches for the correct name when using a heads…
  .gitignore
  pkg/cli/mirror/operator.go
  test/e2e/testcases.sh
Labels: bugzilla/valid-bug, approved, lgtm, jira/valid-bug, jira/severity-moderate

#549 Fix flaky test Valid/OperatorTypeWithRelatedImgs
  pkg/cli/mirror/manifests_test.go
Labels: approved, lgtm, tide/merge-method-squash

#551 CFE-743: Update of golang version from 1.18.6 to 1.19.5
  .ci-operator.yaml
  Dockerfile
  go.mod
  images/cli/Dockerfile.ci
  test/e2e/lib/util.sh
Labels: approved, lgtm, jira/valid-reference
