Repository openshift/oc-mirror, pull requests merged in 2023-09, with the labels that each got.

#676 OCPBUGS-17545: Improve extracting opm binary from catalogs
  pkg/cli/mirror/catalog_images.go
  pkg/cli/mirror/util.go
  pkg/config/metadata.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#694 CFE-955: changes owner file
  OWNERS
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#686 CFE-906: [V2]Enclave support - Separate log file for local storage
  v2/pkg/cli/executor.go
  v2/pkg/mirror/unshare.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/mirror/unshare.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#687 Update list updates CLI documentation
  README.md
Labels: ok-to-test, approved, lgtm, acknowledge-critical-fixes-only

#695 CFE-956: [v2] feat: adds tags on the related images
  v2/README.md
  v2/assets/architecture.png
  v2/pkg/additional/collector.go
  v2/pkg/additional/const.go
  v2/pkg/additional/interface.go
  v2/pkg/additional/local_stored_collector.go
  v2/pkg/additional/new.go
  v2/pkg/cli/executor.go
  v2/pkg/operator/collector.go
  v2/pkg/operator/const.go
  v2/pkg/operator/interface.go
  v2/pkg/operator/local_stored_collector.go
  v2/pkg/operator/new.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/additional/collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/additional/const.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/additional/interface.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/additional/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/additional/new.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/operator/collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/operator/const.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/operator/interface.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/operator/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/operator/new.go
Labels: approved, lgtm, jira/valid-reference

#697 OCPBUGS-17546: pod catalogsource generated by oc-mirror will crashloopBackOff randomly
  pkg/cli/mirror/catalog_images.go
  pkg/image/builder/image_builder.go
  test/e2e/lib/check.sh
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference
