Repository openshift/oc-mirror, pull requests merged in 2023-10, with the labels that each got.

#704 OCPBUGS-7465: Fixes HTTP 401 issues when several catalogs are being mirrored and ne…
  pkg/cli/mirror/operator.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#706 [release-4.14] OCPBUGS-20137: Fixes HTTP 401 issues when several catalogs are being mirrored and ne…
  pkg/cli/mirror/operator.go
Labels: backport-risk-assessed, approved, cherry-pick-approved, qe-approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#702 CFE-960: propose a oc-mirror subcommand that can help prepare mirroring to enclaves
  v2/pkg/additional/collector_test.go
  v2/pkg/additional/new.go
  v2/pkg/batch/worker_test.go
  v2/pkg/cli/executor.go
  v2/pkg/mirror/mirror.go
  v2/pkg/operator/collector_test.go
  v2/pkg/operator/new.go
  v2/pkg/release/collector.go
  v2/pkg/release/collector_test.go
  v2/pkg/release/local_stored_collector.go
  v2/pkg/release/local_stored_collector_test.go
  v2/tests/results/cover.html
  v2/tests/results/cover.out
  vendor/github.com/openshift/oc-mirror/v2/pkg/additional/new.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/mirror/mirror.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/operator/new.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/local_stored_collector.go
Labels: approved, lgtm, jira/valid-reference

#716 Remove Dockerfile.integration - not used - reduce confusion
  images/tests/Dockerfile.integration
Labels: approved, lgtm

#718 CFE-899,CFE-958: feat: removes the registry dns
  v2/pkg/additional/local_stored_collector.go
  v2/pkg/operator/local_stored_collector.go
  v2/pkg/release/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/additional/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/operator/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/local_stored_collector.go
Labels: approved, lgtm, jira/valid-reference

#719 Pr template change
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm

#722 [V2] CFE-971: Generate OSUS graph image - uses go-containerregistry implementation
  v2/pkg/cli/executor.go
  v2/pkg/imagebuilder/builder.go
  v2/pkg/imagebuilder/interface.go
  v2/pkg/release/collector.go
  v2/pkg/release/constants.go
  v2/pkg/release/graph.go
  v2/pkg/release/graph_test.go
  v2/pkg/release/interfaces.go
  v2/pkg/release/local_stored_collector.go
  v2/tests/results/cover.html
  v2/tests/results/cover.out
  vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/imagebuilder/builder.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/imagebuilder/interface.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/constants.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/graph.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/interfaces.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/local_stored_collector.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#709 CFE-965: [V2] Enable signature verification
  .gitignore
  imstcfg.yaml
  v2/README.md
  v2/pkg/additional/collector_test.go
  v2/pkg/batch/worker_test.go
  v2/pkg/cli/executor.go
  v2/pkg/cli/executor_test.go
  v2/pkg/clusterresources/clusterresources_test.go
  v2/pkg/diff/diff.go
  v2/pkg/diff/schema.go
  v2/pkg/mirror/mirror_test.go
  v2/pkg/mirror/options.go
  v2/pkg/operator/collector_test.go
  v2/pkg/release/cincinnati_test.go
  v2/pkg/release/collector_test.go
  v2/pkg/release/local_stored_collector_test.go
  v2/tests/results/cover.out
  vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/diff/diff.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/diff/schema.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/mirror/options.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference
