Repository openshift/oc-mirror, pull requests merged in 2023-04, with the labels that each got.

#598 OCPBUGS-1060 fix: changes confusing error message
  pkg/cli/mirror/publish.go
  pkg/cli/mirror/publish_test.go
Labels: approved, lgtm

#600 OCPBUGS-10348 fix: changes to include the registry path
  pkg/image/resolve.go
Labels: approved, lgtm

#599 OCPBUGS-7845 fix: changes the way the version is shown
  Makefile
  pkg/cli/mirror/version/version.go
Labels: approved, lgtm

#601 OCPBUGS-2633: Fix
  pkg/cli/mirror/mirror.go
Labels: bugzilla/valid-bug, approved, qe-approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#604 OCPBUGS-11552: work around OCPBUGS-6741 by explicitly setting --cache-dir on opm in catalog images
  pkg/cli/mirror/catalog_images.go
Labels: bugzilla/valid-bug, approved, qe-approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#613 OCPBUGS-12236: Revert adding '--cache-dir /tmp/cache' to catalog images
  pkg/cli/mirror/catalog_images.go
Labels: bugzilla/valid-bug, approved, qe-approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#614 OCPBUGS-12437: Update OWNERS for CFE team
  OWNERS
Labels: bugzilla/valid-bug, approved, lgtm, jira/valid-bug, jira/valid-reference

#620 OCPBUGS-12458: Deprecate --use-oci-feature in favor of --include-local-oci-catalogs
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/mirror_test.go
  pkg/cli/mirror/options.go
  test/e2e/testcases.sh
Labels: bugzilla/valid-bug, approved, lgtm, jira/valid-bug, jira/valid-reference

#605 OCPBUGS-4959: oc-mirror error on second synchronisation with no change
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/sequence.go
Labels: bugzilla/valid-bug, approved, lgtm, jira/valid-bug, jira/valid-reference
