Repository openshift/oc-mirror, pull requests merged in 2023-02, with the labels that each got.

#560 Upgrade base image for oc-mirror to 4.13
  images/cli/Dockerfile.ci
Labels: approved, lgtm

#556 Fix typo in diff.go
  pkg/operator/diff/internal/diff.go
Labels: approved, lgtm

#559 CFE-658 - Implementation of filtering by channel for OCI catalog
  pkg/cli/mirror/fbc_operators.go
  pkg/cli/mirror/fbc_operators_test.go
Labels: approved, lgtm

#552 [graph-data] use new cincinnati endpoint to download tarball
  pkg/cli/mirror/cincinnati_graph_image.go
Labels: approved, qe-approved, lgtm

#564 CFE-768: Update to allow for incremental and pruning for oci feature
  imstcfg.yaml
  pkg/api/v1alpha2/types_config.go
  pkg/cli/mirror/additional.go
  pkg/cli/mirror/additional_test.go
  pkg/cli/mirror/catalog_images.go
  pkg/cli/mirror/cincinnati_graph_image.go
  pkg/cli/mirror/create.go
  pkg/cli/mirror/create_test.go
  pkg/cli/mirror/fbc_operators.go
  pkg/cli/mirror/fbc_operators_test.go
  pkg/cli/mirror/manifests_test.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/mirror_test.go
  pkg/cli/mirror/operator.go
  pkg/cli/mirror/publish.go
  pkg/image/association_builder_test.go
  pkg/image/builder/image_builder.go
  pkg/image/convert.go
  pkg/image/convert_test.go
  pkg/image/image.go
  pkg/image/image_test.go
  pkg/image/mapping.go
  pkg/image/mapping_test.go
  pkg/metadata/store.go
  test/e2e/artifacts/configs/index.yaml
  test/e2e/lib/util.sh
  test/e2e/lib/workflow.sh
Labels: approved, lgtm, jira/valid-reference

#555 docs: adds clarification to imageset reference and examples
  docs/design/workflows.md
  docs/examples/imageset-config-catalog-full.yaml
  docs/examples/imageset-config-catalog-headsonly.yaml
  docs/examples/imageset-config-filter-catalog.yaml
  docs/imageset-config-ref.yaml
Labels: approved, lgtm

#565 CFE-764 : Introduce v1alpha2.Operator.TargetCatalog
  pkg/api/v1alpha2/types_config.go
  pkg/api/v1alpha2/types_config_test.go
  pkg/cli/mirror/fbc_operators.go
  pkg/cli/mirror/fbc_operators_test.go
  pkg/cli/mirror/manifests.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/operator.go
  pkg/metadata/store.go
Labels: approved, qe-approved, lgtm
