Repository openshift/oc-mirror, pull requests merged in 2023-08, with the labels that each got.

#667 CFE-904: [v2] Fix unit tests for local storage collector implementation
  v2/pkg/cli/executor.go
  v2/pkg/cli/executor_test.go
  v2/tests/isc.yaml
Labels: approved, lgtm, jira/valid-reference

#668 CFE-905: Make local storage port configurable via command line
  v2/pkg/cli/executor.go
  v2/pkg/mirror/options.go
Labels: approved, lgtm, jira/valid-reference

#660 fixing `oc-mirror version` when run from read-only fs
  pkg/cli/options.go
Labels: ok-to-test, approved, lgtm

#669 add go.mod files to testdata directories
  pkg/cli/mirror/testdata/README.md
  pkg/cli/mirror/testdata/go.mod
  pkg/image/testdata/README.md
  pkg/image/testdata/go.mod
  pkg/metadata/testdata/README.md
  pkg/metadata/testdata/go.mod
Labels: approved, lgtm

#670 CFE-902 feat: adds go workspace to support multi-module
  Makefile
  go.mod
  go.sum
  go.work
  go.work.sum
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/operator_test.go
  pkg/cli/mirror/options.go
  test/e2e/testcases.sh
  v2/Makefile
  v2/README.md
  v2/pkg/mirror/mirror.go
Labels: approved, lgtm

#680 OCPBUGS-17714: Ensure errors are nil before closing registry to avoid…
  pkg/cli/mirror/fbc_operators.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#682 OCPBUGS-14402: Fix case where catalog is on a mirror from registries…
  pkg/cli/mirror/fbc_operators.go
  pkg/cli/mirror/fbc_operators_test.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference
