Repository openshift/oc-mirror, pull requests merged in 2023-07, with the labels that each got.

#658 OCPBUGS-15329: Fix " OCI index found, but accept header does not suppo…"
  pkg/image/association_builder.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#655 OCPBUGS-11754: add cleanup of /tmp directories
  pkg/cli/mirror/mirror.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#663 OCPBUGS-13871 docs: changes the help message for oci-registries-config flag
  pkg/cli/mirror/options.go
Labels: approved, lgtm
