Repository openshift/oc-mirror, pull requests merged in 2023-05, with the labels that each got.

#627 OCPBUGS-13116: Implementation of filtering by channel for OCI catalog
  pkg/cli/mirror/fbc_operators.go
  pkg/cli/mirror/fbc_operators_test.go
  pkg/cli/mirror/operator.go
  test/e2e/testcases.sh
Labels: bugzilla/valid-bug, approved, lgtm

#634 OCPBUGS-11922: paths not needed in ICSPBuilder interface
  pkg/cli/mirror/manifests.go
Labels: bugzilla/valid-bug, approved, lgtm, jira/valid-bug, jira/valid-reference

#633 OCPBUGS-11840: ParseImageReference supports cases where both tag …
  pkg/api/v1alpha2/types_config.go
  pkg/api/v1alpha2/types_config_test.go
Labels: bugzilla/valid-bug, approved, lgtm, jira/valid-bug, jira/valid-reference

#635 [release-4.13] OCPBUGS-13591,OCPBUGS-13592: Limit the nested repository path while mirroring the images
  pkg/cli/mirror/manifests.go
  pkg/cli/mirror/manifests_test.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/mirror_test.go
  pkg/cli/mirror/operator.go
  pkg/cli/mirror/options.go
  pkg/image/mapping.go
  pkg/image/mapping_test.go
Labels: bugzilla/valid-bug, backport-risk-assessed, approved, cherry-pick-approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#638 OCPBUGS-13762: make addRelatedImageToMapping multithreaded
  go.mod
  pkg/cli/mirror/fbc_operators.go
  pkg/cli/mirror/fbc_operators_test.go
  pkg/cli/mirror/operator.go
Labels: bugzilla/valid-bug, approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#644 adds Jeremy Peterson to OWNERS file
  OWNERS
Labels: approved, lgtm, jira/valid-bug

#645 Removes Ross and adds Jeremy in the OWNER file
  OWNERS
Labels: backport-risk-assessed, approved, cherry-pick-approved, lgtm, jira/valid-bug

#646 updates the OWNERS file
  OWNERS
Labels: backport-risk-assessed, approved, cherry-pick-approved, lgtm, jira/valid-bug

#647 changes the OWNERS file
  OWNERS
Labels: backport-risk-assessed, approved, cherry-pick-approved, lgtm, jira/valid-bug

#642 [release-4.12] OCPBUGS-14065: fix: Limit the nested repository path while mirroring the images
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/mirror_test.go
  pkg/cli/mirror/options.go
  pkg/image/mapping.go
  pkg/image/mapping_test.go
Labels: backport-risk-assessed, approved, cherry-pick-approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#641 [release-4.12] OCPBUGS-13432: Got the `file exists` error when different digest direct to the same tag
  pkg/cli/mirror/mirror.go
Labels: backport-risk-assessed, approved, cherry-pick-approved, qe-approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#636 OCPBUGS-13332: Create rfc 1035 compliant catalog source name
  pkg/cli/mirror/manifests.go
  pkg/cli/mirror/manifests_test.go
Labels: bugzilla/valid-bug, approved, qe-approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference
