Repository openshift/oc-mirror, pull requests merged in 2023-12, with the labels that each got.

#742 OTA-914: Adding release payload signatures to graph-data container
  go.mod
  pkg/cli/mirror/cincinnati_graph_image.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/publish.go
  v2/tests/results/cover.out
Labels: approved, lgtm, jira/valid-reference

#755 NO-ISSUE: Make A.Guidi approver on oc-mirror
  OWNERS
Labels: approved, lgtm, jira/valid-reference

#746 OCPBUGS-23340: Add generation of updateService.yaml
  v2/pkg/archive/archive_test.go
  v2/pkg/cli/executor.go
  v2/pkg/cli/executor_test.go
  v2/pkg/clusterresources/clusterresources.go
  v2/pkg/clusterresources/clusterresources_test.go
  v2/pkg/clusterresources/const.go
  v2/pkg/clusterresources/interface.go
  v2/pkg/clusterresources/updateservice/v1/groupversion_info.go
  v2/pkg/clusterresources/updateservice/v1/updateservice_types.go
  v2/pkg/release/collector.go
  v2/pkg/release/collector_test.go
  v2/pkg/release/error.go
  v2/pkg/release/interface.go
  v2/pkg/release/local_stored_collector.go
  v2/pkg/release/local_stored_collector_test.go
  v2/tests/working-dir-fake/release-filters/690d64d2ebd41f1834c80e632f041b5b
  vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/clusterresources/clusterresources.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/clusterresources/const.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/clusterresources/interface.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/clusterresources/updateservice/v1/groupversion_info.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/clusterresources/updateservice/v1/updateservice_types.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/error.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/interface.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/local_stored_collector.go
  vendor/modules.txt
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#751 OCPBUGS-23550: - oc-mirror on RHEL9 Host with FIPS enabled
  .ci-operator.yaml
  Dockerfile
  images/cli/Dockerfile.ci
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#753 OCPBUGS-24359: Fix including duplicate blobs in archive
  v2/pkg/archive/archive.go
  v2/pkg/archive/archive_test.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/archive/archive.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#750 OCPBUGS-24357: Move logs folder under workingDir
  .gitignore
  v2/pkg/batch/worker.go
  v2/pkg/batch/worker_test.go
  v2/pkg/cli/executor.go
  v2/pkg/operator/collector.go
  v2/pkg/operator/local_stored_collector.go
  v2/pkg/operator/new.go
  v2/pkg/release/collector.go
  v2/pkg/release/const.go
  v2/pkg/release/local_stored_collector.go
  v2/pkg/release/new.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/batch/worker.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/operator/collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/operator/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/operator/new.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/const.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/new.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#761 OCPBUGS-21865: Honor IncludeChannel.MaxVersion when mirroring differe…
  pkg/operator/declcfg_to_includecfg.go
  pkg/operator/declfg_to_includecfg_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
