Repository openshift/oc-mirror, pull requests merged in 2023-03, with the labels that each got.

#562 CFE-749: add e2e test for oci catalog feature to include release and additiona…
  pkg/cincinnati/client.go
  test/e2e/configs/imageset-config-oci-mirror-all.yaml
  test/e2e/e2e-simple.sh
  test/e2e/graph/cincinnatti.json
  test/e2e/graph/main.go
  test/e2e/lib/util.sh
  test/e2e/lib/workflow.sh
  test/e2e/testcases.sh
Labels: approved, lgtm, jira/valid-reference

#567 CFE-739: Add skip pruning flag and logic
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/options.go
  pkg/cli/mirror/prune.go
Labels: approved, lgtm, jira/valid-reference

#569 CFE-768 - FollowUp: Fix usage of registries.conf for OCI feature
  pkg/cli/mirror/fbc_operators.go
  pkg/cli/mirror/fbc_operators_test.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/operator.go
Labels: approved, lgtm

#574 docs: add information about unsupported scenario
  TROUBLESHOOTING.md
  pkg/cli/mirror/fbc_operators.go
  pkg/image/image.go
Labels: approved, lgtm

#579 OCPBUGS-8216: fix: remove an unecessary error message
  pkg/image/image.go
Labels: bugzilla/valid-bug, approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#582 OCPBUGS-7888: fix extract dir for cincinnati-graph-data container
  pkg/cli/mirror/cincinnati_graph_image.go
Labels: bugzilla/valid-bug, approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#572 OCPBUGS-8111: Bugfix for destination registry nested paths length
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/mirror_test.go
  pkg/cli/mirror/options.go
Labels: bugzilla/valid-bug, approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#586 OCPBUGS-10051: fix: remove catalog from ImageContentSourcePolicy.yaml
  pkg/cli/mirror/mirror.go
Labels: bugzilla/valid-bug, approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#573 OCPBUGS-8276: Bugfix check imagesetconfig for valid oci protocol when oci feature i…
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/mirror_test.go
Labels: bugzilla/valid-bug, approved, qe-approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#591 [release-4.12] OCPBUGS-863: Add skip pruning flag and logic
  pkg/cli/mirror/manifests_test.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/options.go
  pkg/cli/mirror/prune.go
Labels: bugzilla/valid-bug, backport-risk-assessed, approved, cherry-pick-approved, qe-approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference
