Repository openshift/oc-mirror, pull requests merged in 2023-06, with the labels that each got.

#652 OCPBUGS-14402: fix
  pkg/cli/mirror/fbc_operators.go
  pkg/cli/mirror/mirror.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#649 OCPBUGS-14194: fix oc-mirror should check metadata sequence when --include-local-oci-catalogs is used
  pkg/cli/mirror/mirror.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#603 OCPBUGS-588: minVersion in ImageSetConfiguration seems to be ignored
  pkg/operator/diff/internal/diff_include.go
Labels: bugzilla/valid-bug, approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#653 OCPBUGS-13871: fix: changes on help info content
  pkg/cli/mirror/options.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#624 MULTIARCH-3440: refine multiarch support for test-unit and test-e2e using dockerfile and add ppc64le build to Makefile
  .goreleaser.yaml
  Dockerfile
  Makefile
  test/e2e/e2e-simple.sh
  test/e2e/lib/util.sh
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#622 CFE-859: Removing flag use-oci-feature starting release-4.14
  pkg/cli/mirror/options.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#585 Replacing the hard coded path with graphDataMountPath
  pkg/cli/mirror/cincinnati_graph_image.go
Labels: approved, lgtm

#657 MIXEDARCH-265: Enable mirroring of the multi release image
  docs/design/imageset-configuration.md
  docs/examples/imageset-config-release-alt-arch.yaml
  docs/imageset-config-ref.yaml
  pkg/cli/mirror/list/releases.go
  pkg/cli/mirror/release.go
Labels: approved, lgtm, jira/valid-reference
