Repository openshift/oc-mirror, pull requests merged in 2023-11, with the labels that each got.

#726 NO-ISSUE: Cancel community office hours: none for the moment
  README.md
Labels: approved, lgtm, jira/valid-reference

#725 OCPBUGS-22947: Should not generate graph with prepare subcommand
  v2/pkg/cli/executor.go
  v2/pkg/release/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/local_stored_collector.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#728 CFE-959: refactorings
  v2/pkg/additional/collector.go
  v2/pkg/additional/collector_test.go
  v2/pkg/additional/const.go
  v2/pkg/additional/local_stored_collector.go
  v2/pkg/batch/worker_test.go
  v2/pkg/cli/executor.go
  v2/pkg/cli/executor_test.go
  v2/pkg/clusterresources/clusterresources_test.go
  v2/pkg/image/image.go
  v2/pkg/mirror/const.go
  v2/pkg/mirror/mirror.go
  v2/pkg/mirror/mirror_test.go
  v2/pkg/mirror/options.go
  v2/pkg/operator/collector.go
  v2/pkg/operator/collector_test.go
  v2/pkg/operator/const.go
  v2/pkg/operator/local_stored_collector.go
  v2/pkg/release/cincinnati.go
  v2/pkg/release/cincinnati_test.go
  v2/pkg/release/client.go
  v2/pkg/release/collector.go
  v2/pkg/release/collector_test.go
  v2/pkg/release/const.go
  v2/pkg/release/constants.go
  v2/pkg/release/core-cincinnati.go
  v2/pkg/release/core-cincinnati_test.go
  v2/pkg/release/graph.go
  v2/pkg/release/graph_test.go
  v2/pkg/release/interface.go
  v2/pkg/release/interfaces.go
  v2/pkg/release/local_stored_collector.go
  v2/pkg/release/local_stored_collector_test.go
  v2/pkg/release/new.go
  v2/pkg/release/signature.go
  v2/tests/results/cover.out
  vendor/github.com/openshift/oc-mirror/v2/pkg/additional/collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/additional/const.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/additional/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/image/image.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/mirror/const.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/mirror/mirror.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/mirror/options.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/operator/collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/operator/const.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/operator/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/cincinnati.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/client.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/const.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/constants.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/core-cincinnati.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/graph.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/interface.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/interfaces.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/new.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/signature.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#731 NO-ISSUE: Package ioutil is deprecated as of Go 1.16
  pkg/api/v1alpha1/config_test.go
  pkg/api/v1alpha1/metadata_test.go
  pkg/archive/archive_test.go
  pkg/bundle/files.go
  pkg/bundle/files_test.go
  pkg/cincinnati/cincinnati.go
  pkg/cli/options.go
  pkg/config/load.go
  pkg/config/load_test.go
  v2/tests/results/cover.out
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#733 PROJQUAY-6345: Skipping mirror failure if manifest not found during prune
  pkg/cli/mirror/prune.go
  pkg/cli/mirror/prune_test.go
Labels: ok-to-test, approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#736 CFE-977, CFE-978, CFE-982: Introduce history interface with its Reader and Append implementation
  v2/pkg/history/const.go
  v2/pkg/history/history.go
  v2/pkg/history/history_test.go
  v2/pkg/history/interface.go
  v2/tests/.history-fake/.history-2023-11-21T11:47:46Z
  v2/tests/.history-fake/.history-2023-11-22T11:24:14Z
  v2/vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#738 CFE-977,CFE-981: unarchiver interface and its implementation
  v2/pkg/archive/const.go
  v2/pkg/archive/interface.go
  v2/pkg/archive/unarchive.go
  v2/pkg/archive/unarchive_test.go
  v2/pkg/release/local_stored_collector_test.go
  v2/tests/results/cover.out
  v2/tests/working-dir-fake/hold-release/ocp-release/4.14.1-x86_64/release-manifests/image-references
  v2/tests/working-dir-fake/hold-release/ocp-release/4.14.1-x86_64/release-manifests/release-metadata
  v2/tests/working-dir-fake/release-filters/d5f8153de54b0327ad20d24d4dbba7a6
Labels: approved, lgtm, jira/valid-reference

#740 CFE-977,CFE-992: Integrate all the building blocks together - Disk to Mirror
  v2/pkg/additional/local_stored_collector.go
  v2/pkg/archive/archive_test.go
  v2/pkg/archive/unarchive.go
  v2/pkg/cli/executor.go
  v2/pkg/cli/executor_test.go
  v2/pkg/operator/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/additional/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/archive/unarchive.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/operator/local_stored_collector.go
Labels: approved, lgtm, jira/valid-reference

#745 OCPBUGS-24243: remove unnecessary print statement from pkg/cli/options.go
  pkg/cli/options.go
Labels: ok-to-test, approved, lgtm, jira/valid-bug, jira/valid-reference

#743 OCPBUGS-23339: fix IDMS custom resource name
  v2/pkg/clusterresources/clusterresources.go
  v2/pkg/clusterresources/clusterresources_test.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/clusterresources/clusterresources.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
