Repository openshift/oc-mirror, pull requests merged in 2024-06, with the labels that each got.

#867 OCPBUGS-33121: Fix problems with versions and verbose flags
  pkg/cli/mirror/mirror.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#869 OCPBUGS-33775: Do not generate idms & itms if nothing has been mirrored
  v2/internal/pkg/clusterresources/clusterresources.go
  v2/internal/pkg/clusterresources/clusterresources_test.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/clusterresources/clusterresources.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#872 OCPBUGS-34330: Updating oc-mirror-plugin-container image to be consistent with ART for 4.17
  .ci-operator.yaml
  go.mod
  images/cli/Dockerfile.ci
  v2/go.mod
  v2/go.sum
  vendor/github.com/golang-migrate/migrate/v4/source/iofs/testdata/migrations/1_foobar.down.sql
  vendor/github.com/golang-migrate/migrate/v4/source/iofs/testdata/migrations/1_foobar.up.sql
  vendor/github.com/golang-migrate/migrate/v4/source/iofs/testdata/migrations/3_foobar.up.sql
  vendor/github.com/golang-migrate/migrate/v4/source/iofs/testdata/migrations/4_foobar.down.sql
  vendor/github.com/golang-migrate/migrate/v4/source/iofs/testdata/migrations/4_foobar.up.sql
  vendor/github.com/golang-migrate/migrate/v4/source/iofs/testdata/migrations/5_foobar.down.sql
  vendor/github.com/golang-migrate/migrate/v4/source/iofs/testdata/migrations/7_foobar.down.sql
  vendor/github.com/golang-migrate/migrate/v4/source/iofs/testdata/migrations/7_foobar.up.sql
  vendor/github.com/operator-framework/operator-registry/alpha/action/testdata/foo-bundle-v0.1.0/manifests/foo.v0.1.0.csv.yaml
  vendor/github.com/operator-framework/operator-registry/alpha/action/testdata/foo-bundle-v0.1.0/manifests/foos.test.foo.crd.yaml
  vendor/github.com/operator-framework/operator-registry/alpha/action/testdata/foo-bundle-v0.1.0/metadata/annotations.yaml
  vendor/github.com/operator-framework/operator-registry/alpha/action/testdata/foo-bundle-v0.1.0/metadata/dependencies.yaml
  vendor/github.com/operator-framework/operator-registry/alpha/action/testdata/foo-bundle-v0.2.0-no-csv-related-images/manifests/foo.v0.2.0.csv.yaml
  vendor/github.com/operator-framework/operator-registry/alpha/action/testdata/foo-bundle-v0.2.0-no-csv-related-images/manifests/foos.test.foo.crd.yaml
  vendor/github.com/operator-framework/operator-registry/alpha/action/testdata/foo-bundle-v0.2.0-no-csv-related-images/metadata/annotations.yaml
  vendor/github.com/operator-framework/operator-registry/alpha/action/testdata/foo-bundle-v0.2.0-no-csv-related-images/metadata/dependencies.yaml
  vendor/github.com/operator-framework/operator-registry/alpha/action/testdata/foo-bundle-v0.2.0/manifests/foo.v0.2.0.csv.yaml
  vendor/github.com/operator-framework/operator-registry/alpha/action/testdata/foo-bundle-v0.2.0/manifests/foos.test.foo.crd.yaml
  vendor/github.com/operator-framework/operator-registry/alpha/action/testdata/foo-bundle-v0.2.0/metadata/annotations.yaml
  vendor/github.com/operator-framework/operator-registry/alpha/action/testdata/foo-bundle-v0.2.0/metadata/dependencies.yaml
  vendor/github.com/operator-framework/operator-registry/alpha/action/testdata/foo-index-v0.2.0-declcfg/foo/index.yaml
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#877 OCPBUGS-35279: Fix spelling error in delete console message
  v2/internal/pkg/cli/delete.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/delete.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#874 CLID-135: Show warning in console when EUS & version conditions used
  pkg/cli/mirror/release.go
  v2/internal/pkg/release/cincinnati.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/cincinnati.go
Labels: approved, lgtm, jira/valid-reference

#865 OCPBUGS-34020: Implement fail safe / fail fast in workers
  v2/internal/pkg/batch/error.go
  v2/internal/pkg/batch/worker.go
  v2/internal/pkg/batch/worker_test.go
  v2/internal/pkg/cli/additional_integration_test.go
  v2/internal/pkg/cli/delete.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/cli/executor_test.go
  v2/internal/pkg/cli/release_integration_test.go
  v2/internal/pkg/clusterresources/clusterresources.go
  v2/internal/pkg/delete/delete_images.go
  v2/internal/pkg/delete/delete_images_test.go
  v2/internal/pkg/mirror/mirror.go
  v2/internal/testutils/testutils.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/batch/error.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/batch/worker.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/delete.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/clusterresources/clusterresources.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/delete/delete_images.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/mirror/mirror.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#878 NO-ISSUE: Update enclave documentation : OSUS
  v2/docs/enclave_support.md
Labels: approved, lgtm, jira/valid-reference
