Repository openshift/oc-mirror, pull requests merged in 2024-02, with the labels that each got.

#792 NO-ISSUE: Fix documentation diagram
  v2/assets/S4-ISC_V2.jpg
Labels: approved, lgtm, jira/valid-reference

#790 [release-4.14] OCPBUGS-28871: Capability to override default channel …
  .gitignore
  pkg/api/v1alpha2/types_include_config.go
  pkg/cli/mirror/mirror.go
  pkg/operator/diff/diff.go
  pkg/operator/diff/internal/diff.go
  pkg/operator/diff/internal/diff_include.go
  pkg/operator/diff/internal/diff_test.go
  v2/pkg/mirror/unshare.go
  v2/tests/results/cover.html
  v2/tests/results/cover.out
  vendor/github.com/openshift/oc-mirror/v2/pkg/mirror/unshare.go
Labels: backport-risk-assessed, approved, cherry-pick-approved, qe-approved, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference

#789 CLID-9,CLID-21,CLID-22: Respect archive max size
  v2/pkg/archive/adder_common.go
  v2/pkg/archive/archive.go
  v2/pkg/archive/archive_test.go
  v2/pkg/archive/const.go
  v2/pkg/archive/interface.go
  v2/pkg/archive/permissive_adder.go
  v2/pkg/archive/permissive_adder_test.go
  v2/pkg/archive/strict_adder.go
  v2/pkg/archive/strict_adder_test.go
  v2/pkg/archive/unarchive.go
  v2/pkg/archive/unarchive_test.go
  v2/pkg/cli/executor.go
  v2/pkg/cli/executor_test.go
  v2/pkg/mirror/options.go
  v2/tests/archive-test-data/0000_03_config-operator_01_proxy.crd.yaml
  v2/tests/archive-test-data/0000_03_marketplace-operator_01_operatorhub.crd.yaml
  v2/tests/archive-test-data/0000_03_securityinternal-openshift_02_rangeallocation.crd.yaml
  vendor/github.com/openshift/oc-mirror/v2/pkg/archive/adder_common.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/archive/archive.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/archive/const.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/archive/interface.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/archive/permissive_adder.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/archive/strict_adder.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/archive/unarchive.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/mirror/options.go
Labels: approved, lgtm, jira/valid-reference

#791 [release-4.13] OCPBUGS-28899: Capability to override default channel
  pkg/api/v1alpha2/types_include_config.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/mirror_test.go
  pkg/operator/diff/diff.go
  pkg/operator/diff/internal/diff.go
  pkg/operator/diff/internal/diff_include.go
  pkg/operator/diff/internal/diff_test.go
Labels: backport-risk-assessed, approved, cherry-pick-approved, qe-approved, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference

#795 CLID-9,CLID-24: Support incremental mirroring using archives by date
  v2/pkg/archive/archive.go
  v2/pkg/archive/permissive_adder.go
  v2/pkg/cli/executor.go
  v2/pkg/cli/executor_test.go
  v2/pkg/clusterresources/clusterresources.go
  v2/pkg/mirror/options.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/archive/archive.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/archive/permissive_adder.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/clusterresources/clusterresources.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/mirror/options.go
Labels: approved, lgtm, jira/valid-reference

#796 [release-4.12] OCPBUGS-29232: Capability to override default channel
  pkg/api/v1alpha2/types_include_config.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/mirror_test.go
  pkg/operator/diff/diff.go
  pkg/operator/diff/internal/diff.go
  pkg/operator/diff/internal/diff_include.go
  pkg/operator/diff/internal/diff_test.go
Labels: backport-risk-assessed, approved, cherry-pick-approved, qe-approved, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference

#801 CLID-9,CLID-23: feat: hide unnecessary flags
  v2/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only
