Repository openshift/oc-mirror, pull requests merged in 2024-08, with the labels that each got.

#903 OCPBUGS-37861: removes duplicated operator related images
  v2/internal/pkg/operator/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/operator/local_stored_collector.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#900 [v2] CLID-179: Include the HyperShift KubeVirt CoreOS container
  v2/internal/pkg/api/v2alpha1/type_config.go
  v2/internal/pkg/api/v2alpha1/type_image.go
  v2/internal/pkg/api/v2alpha1/type_kubevirt.go
  v2/internal/pkg/release/const.go
  v2/internal/pkg/release/local_stored_collector.go
  v2/internal/pkg/release/local_stored_collector_test.go
  v2/tests/0000_50_installer_coreos-bootimages.yaml
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/api/v2alpha1/type_config.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/api/v2alpha1/type_image.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/api/v2alpha1/type_kubevirt.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/const.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/local_stored_collector.go
Labels: approved, lgtm, jira/valid-reference

#899 OCPBUGS-37667: Rebuild catalogs -- without cache generation
  pkg/cli/mirror/catalog_images.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/operator.go
  pkg/cli/mirror/options.go
  test/e2e/testcases.sh
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#904 OCPBUGS-37950: Bug fix when kubevirt image not found
  v2/internal/pkg/release/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/local_stored_collector.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#909 [v2] OCPBUGS-38396: use platform.release when set
  v2/internal/pkg/release/cincinnati.go
  v2/internal/pkg/release/cincinnati_test.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/cincinnati.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#906 OCPBUGS-38037: unable to build graph image in enclave environment
  v2/go.mod
  v2/internal/e2e/templates/isc_templates/release_isc.yaml
  v2/internal/pkg/additional/local_stored_collector_test.go
  v2/internal/pkg/additional/new.go
  v2/internal/pkg/api/v2alpha1/type_image.go
  v2/internal/pkg/batch/concurrent_worker.go
  v2/internal/pkg/batch/concurrent_worker_test.go
  v2/internal/pkg/cli/additional_integration_test.go
  v2/internal/pkg/cli/delete.go
  v2/internal/pkg/cli/delete_test.go
  v2/internal/pkg/cli/dryrun_test.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/cli/executor_test.go
  v2/internal/pkg/cli/release_integration_test.go
  v2/internal/pkg/delete/delete_images_test.go
  v2/internal/pkg/delete/new.go
  v2/internal/pkg/mirror/mirror.go
  v2/internal/pkg/mirror/mirror_test.go
  v2/internal/pkg/mirror/options.go
  v2/internal/pkg/operator/local_stored_collector_test.go
  v2/internal/pkg/operator/new.go
  v2/internal/pkg/release/cincinnati.go
  v2/internal/pkg/release/client_test.go
  v2/internal/pkg/release/core-cincinnati_test.go
  v2/internal/pkg/release/graph.go
  v2/internal/pkg/release/graph_test.go
  v2/internal/pkg/release/local_stored_collector.go
  v2/internal/pkg/release/local_stored_collector_test.go
  v2/internal/pkg/release/new.go
  v2/internal/pkg/release/signature_test.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/additional/new.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/api/v2alpha1/type_image.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/batch/concurrent_worker.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/delete.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/delete/new.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/mirror/mirror.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/mirror/options.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/operator/new.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/cincinnati.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/graph.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/new.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#911 OCPBUGS-37867: Use tag only when image by tag and digest
  v2/internal/pkg/additional/local_stored_collector.go
  v2/internal/pkg/additional/local_stored_collector_test.go
  v2/internal/pkg/image/image.go
  v2/internal/pkg/image/image_test.go
  v2/internal/pkg/operator/local_stored_collector.go
  v2/internal/pkg/operator/local_stored_collector_test.go
  v2/internal/pkg/release/signature.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/additional/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/image/image.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/operator/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/signature.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#907 CLID-169: Add terraform template to up Enclave demo env on AWS
  v2/internal/e2e/infra_demo/main.tf
  v2/internal/e2e/infra_demo/user_data.sh
Labels: approved, lgtm, jira/valid-reference

#908 OCPBUGS-35824: Log warning UPDATE_URL_OVERRIDE correctly
  v2/internal/pkg/cli/delete.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/release/cincinnati.go
  v2/internal/pkg/release/cincinnati_test.go
  v2/internal/pkg/release/client.go
  v2/internal/pkg/release/client_test.go
  v2/internal/pkg/release/core-cincinnati.go
  v2/internal/pkg/release/core-cincinnati_test.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/delete.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/cincinnati.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/client.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/core-cincinnati.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference
