Repository openshift/oc-mirror, pull requests merged in 2024-10, with the labels that each got.

#932 [release-4.17] OCPBUGS-42421: oc-mirror skips images with digest and tag
  v2/internal/pkg/additional/local_stored_collector.go
  v2/internal/pkg/additional/local_stored_collector_test.go
  v2/internal/pkg/image/image.go
  v2/internal/pkg/image/image_test.go
  v2/internal/pkg/operator/local_stored_collector.go
  v2/internal/pkg/operator/local_stored_collector_test.go
  v2/internal/pkg/release/signature.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/additional/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/image/image.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/operator/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/signature.go
Labels: backport-risk-assessed, approved, cherry-pick-approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#935 OCPSTRAT-1439,CLID-28,CLID-170: adds feature to mirror helm charts in oc-mirror v2
  v2/go.mod
  v2/go.sum
  v2/internal/pkg/api/v2alpha1/type_image.go
  v2/internal/pkg/api/v2alpha1/type_internal.go
  v2/internal/pkg/batch/concurrent_worker.go
  v2/internal/pkg/cli/const.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/cli/executor_test.go
  v2/internal/pkg/helm/const.go
  v2/internal/pkg/helm/interface.go
  v2/internal/pkg/helm/local_stored_collector.go
  v2/internal/pkg/helm/local_stored_collector_test.go
  v2/internal/pkg/helm/new.go
  v2/tests/helm-data/charts/podinfo-5.0.0.tgz
  v2/tests/helm-data/charts/service-binding-operator-1.0.0.tgz
  v2/tests/helm-data/charts/service-binding-operator-1.0.1.tgz
  v2/tests/helm-data/charts/service-binding-operator-1.0.2.tgz
  v2/tests/helm-data/charts/service-binding-operator-1.1.0.tgz
  v2/tests/helm-data/charts/service-binding-operator-1.3.0.tgz
  v2/tests/helm-data/charts/service-binding-operator-1.3.1.tgz
  v2/tests/helm-data/charts/service-binding-operator-1.3.2.tgz
  v2/tests/helm-data/charts/service-binding-operator-1.3.3.tgz
  v2/tests/helm-data/charts/service-binding-operator-1.4.0.tgz
  v2/tests/helm-data/charts/service-binding-operator-1.4.1.tgz
  v2/tests/helm-data/indexes/redhat-developer.github.io/service-binding-operator-helm-chart/index.yaml
Labels: approved, lgtm, jira/valid-reference

#934 OCPBUGS-42428: Fix duplication of binary data in signature config map
  v2/internal/pkg/clusterresources/clusterresources.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#936 CLID-247: changes the tlsVerify default to true and adds helm tls support
  v2/internal/pkg/archive/image-blob-gatherer.go
  v2/internal/pkg/cli/delete.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/helm/local_stored_collector.go
  v2/internal/pkg/helm/local_stored_collector_test.go
  v2/internal/pkg/helm/new.go
  v2/internal/pkg/mirror/options.go
  v2/internal/pkg/mirror/options_test.go
Labels: approved, lgtm, jira/valid-reference

#940 CLID-174: Use io.MultiWriter for the logger - logs to both stdout and…
  go.work.sum
  v2/internal/pkg/cli/delete.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/cli/executor_test.go
Labels: approved, lgtm, jira/valid-reference

#941 CLID-253: adds helm images to delete feature
  v2/internal/pkg/api/v2alpha1/type_internal.go
  v2/internal/pkg/batch/concurrent_worker.go
  v2/internal/pkg/cli/delete.go
  v2/internal/pkg/cli/delete_test.go
  v2/internal/pkg/delete/delete_images.go
  v2/internal/pkg/helm/new.go
Labels: approved, lgtm, jira/valid-reference

#937 CLID-230: Rebuild catalog multi-arch images with filtered content
  cmd/oc-mirror/main.go
  go.mod
  go.sum
  go.work.sum
  test/e2e/e2e-simple.sh
  v2/cmd/oc-mirror/main.go
  v2/go.mod
  v2/go.sum
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/imagebuilder/builder.go
  v2/internal/pkg/imagebuilder/builder_test.go
  v2/internal/pkg/imagebuilder/interface.go
  v2/internal/pkg/imagebuilder/rebuild_catalog.go
  v2/internal/pkg/mirror/unshare.go
  v2/internal/pkg/release/graph_test.go
  v2/pkg/cli/cli_wrapper.go
  v2/sonar-project.properties
Labels: approved, lgtm, jira/valid-reference
