Repository openshift/oc-mirror, pull requests merged in 2024-01, with the labels that each got.

#770 OCPBUGS-23003: Fix to ensure operator not found error exits with correct status
  pkg/cli/mirror/operator.go
  pkg/cli/mirror/operator_test.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#773 OCPBUGS-16801: fix: fixes the bug on catalog when using field archiveSize: 1
  pkg/cli/mirror/publish.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#771 CLID-4: Add documentation for enclave support
  docs/enclave_support.md
  docs/usage.md
  v2/assets/enclave_support_flow.jpg
Labels: approved, lgtm, jira/valid-reference

#767 OCPBUGS-23550: Generate both binaries for rhel8 and rhel9
  .ci-operator.yaml
  images/cli/Dockerfile.ci
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#778 CLID-14: Add study results in docs
  docs/design/v2/operator-filtering-study.md
  v2/assets/S4-ISC_V2.jpg
Labels: approved, lgtm, jira/valid-reference

#772 OCPBUGS-26513: Add Type for CopyImageSchema; Skip graph for IDMS; Fix UpdateService
  v2/pkg/api/v1alpha3/types.go
  v2/pkg/clusterresources/clusterresources.go
  v2/pkg/clusterresources/const.go
  v2/pkg/manifest/oci-manifest.go
  v2/pkg/operator/const.go
  v2/pkg/release/local_stored_collector.go
  v2/pkg/release/local_stored_collector_test.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/api/v1alpha3/types.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/clusterresources/clusterresources.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/clusterresources/const.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/manifest/oci-manifest.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/operator/const.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/local_stored_collector.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#782 CLID-14: docs: add 3 new scenarios for catalog filtering
  docs/design/v2/operator-filtering-study.md
Labels: approved, lgtm, jira/valid-reference

#785 CLID-14: docs: adds 2 new scenarios
  docs/design/v2/operator-filtering-study.md
Labels: approved, lgtm, jira/valid-reference

#788 NO-ISSUE: Make EnclaveSupport a DevPreview
  docs/enclave_support.md
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#781 CLID-10: IDMS/ITMS
  pkg/cli/mirror/mirror_test.go
  v2/go.mod
  v2/pkg/cli/executor.go
  v2/pkg/cli/executor_test.go
  v2/pkg/clusterresources/clusterresources.go
  v2/pkg/clusterresources/clusterresources_test.go
  v2/pkg/clusterresources/interface.go
  v2/pkg/image/image.go
  v2/pkg/image/image_test.go
  v2/pkg/mirror/options.go
  v2/vendor/github.com/google/go-containerregistry/pkg/v1/random/doc.go
  v2/vendor/github.com/google/go-containerregistry/pkg/v1/random/image.go
  v2/vendor/github.com/google/go-containerregistry/pkg/v1/random/index.go
  v2/vendor/github.com/google/go-containerregistry/pkg/v1/random/options.go
  v2/vendor/modules.txt
  vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/clusterresources/clusterresources.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/clusterresources/interface.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/image/image.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/mirror/options.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#784 CLID-10: Generate CatalogSource files
  v2/go.mod
  v2/go.sum
  v2/pkg/additional/local_stored_collector.go
  v2/pkg/api/operator-framework/v1alpha1/catalogsource_types.go
  v2/pkg/api/v1alpha2/types_config.go
  v2/pkg/api/v1alpha3/types.go
  v2/pkg/cli/executor.go
  v2/pkg/cli/executor_test.go
  v2/pkg/clusterresources/clusterresources.go
  v2/pkg/clusterresources/clusterresources_test.go
  v2/pkg/clusterresources/interface.go
  v2/pkg/config/load_test.go
  v2/pkg/config/validate_test.go
  v2/pkg/manifest/oci-manifest.go
  v2/pkg/operator/local_stored_collector.go
  v2/tests/catalog-source_template.yaml
  v2/tests/catalog-source_template_KO.yaml
  v2/tests/catalog-source_template_KO2.yaml
  v2/vendor/github.com/openshift/library-go/LICENSE
  v2/vendor/github.com/openshift/library-go/pkg/image/internal/digest/digest.go
  v2/vendor/github.com/openshift/library-go/pkg/image/internal/digest/digester.go
  v2/vendor/github.com/openshift/library-go/pkg/image/internal/digest/doc.go
  v2/vendor/github.com/openshift/library-go/pkg/image/internal/reference/doc.go
  v2/vendor/github.com/openshift/library-go/pkg/image/internal/reference/reference.go
  v2/vendor/github.com/openshift/library-go/pkg/image/internal/reference/regexp.go
  v2/vendor/github.com/openshift/library-go/pkg/image/reference/reference.go
  v2/vendor/modules.txt
  vendor/github.com/openshift/oc-mirror/v2/pkg/additional/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/api/operator-framework/v1alpha1/catalogsource_types.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/api/v1alpha2/types_config.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/api/v1alpha3/types.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/clusterresources/clusterresources.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/clusterresources/interface.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/manifest/oci-manifest.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/operator/local_stored_collector.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only
