Repository openshift/oc-mirror, pull requests merged in 2024-11, with the labels that each got.

#942 CLID-269: adds dependabot.yml config file for dependabot
  .github/dependabot.yml
Labels: approved, lgtm, jira/valid-reference

#944 CLID-258: Reduce the number of arguments from NewBuilder
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/imagebuilder/builder.go
  v2/internal/pkg/imagebuilder/builder_test.go
Labels: approved, lgtm, jira/valid-reference

#945 CLID-265,CLID-259,CLID-262: generates folders based on the filtered catalog digest
  v2/internal/pkg/api/v2alpha1/type_image.go
  v2/internal/pkg/api/v2alpha1/type_internal.go
  v2/internal/pkg/cli/const.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/image/image.go
  v2/internal/pkg/imagebuilder/interface.go
  v2/internal/pkg/imagebuilder/rebuild_catalog.go
  v2/internal/pkg/operator/common.go
  v2/internal/pkg/operator/const.go
  v2/internal/pkg/operator/filtered_collector.go
  v2/internal/pkg/release/graph_test.go
Labels: approved, lgtm, jira/valid-reference

#946 CLID-272: adds a deprecated message for oc-mirror v1
  pkg/cli/mirror/mirror.go
Labels: approved, lgtm, jira/valid-reference

#948 CLID-264: removes the default values from the struct definition
  v2/internal/pkg/imagebuilder/rebuild_catalog.go
Labels: approved, lgtm, jira/valid-reference

#949 CLID-263: redirects the rebuild error to a rebuild-error.log
  v2/internal/pkg/imagebuilder/rebuild_catalog.go
Labels: approved, lgtm, jira/valid-reference

#950 CLID-273: Override default container rootless storage path
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/imagebuilder/rebuild_catalog.go
  v2/internal/pkg/mirror/options.go
Labels: approved, lgtm, jira/valid-reference

#943 CLID-270: Implement catalog rebuild based on go-containerregistry
  cmd/oc-mirror/main.go
  go.mod
  go.sum
  v2/go.sum
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/imagebuilder/builder.go
  v2/internal/pkg/imagebuilder/builder_test.go
  v2/internal/pkg/imagebuilder/catalog_builder.go
  v2/internal/pkg/imagebuilder/interface.go
  v2/internal/pkg/imagebuilder/rebuild_catalog.go
  v2/internal/pkg/operator/common.go
  v2/internal/pkg/operator/filtered_collector.go
  v2/internal/pkg/release/graph.go
  v2/internal/pkg/release/graph_test.go
Labels: approved, lgtm, jira/valid-reference

#952 CLID-276: changes the delete feature to use the new collector
  v2/internal/pkg/cli/delete.go
Labels: approved, lgtm, jira/valid-reference

#951 CLID-275: Fix Catalog rebuild in Mirror To Mirror workflow
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/operator/common.go
  v2/internal/pkg/operator/common_test.go
  v2/internal/pkg/operator/filtered_collector.go
  v2/internal/pkg/operator/filtered_collector_test.go
  v2/internal/pkg/operator/interface.go
Labels: approved, lgtm, jira/valid-reference

#954 OCPBUGS-44225,CLID-271: Manage rebuilding OCI catalogs
  v2/internal/pkg/clusterresources/clusterresources.go
  v2/internal/pkg/operator/filtered_collector.go
  v2/internal/pkg/operator/filtered_collector_test.go
  v2/tests/oci-image/blobs/sha256/81df7ff16254ed9756e27c8de9ceb02a9568228fccadbf080f41cc5eb5118a44
  v2/tests/oci-image/blobs/sha256/b5632fc886395e5595e9aed61f2e8473079fb81666f229ec5c3772d2ee64c389
  v2/tests/oci-image/blobs/sha256/e68bec78a65b807f09c1c0d4f47a7dd3e8e8aeb7c1cd9038a014c68bcf576cd7
  v2/tests/oci-image/index.json
  v2/tests/oci-image/oci-layout
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#953 CLID-261,CLID-274: rebuild independently of collect
  v2/go.sum
  v2/internal/pkg/batch/concurrent_worker.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/imagebuilder/catalog_builder.go
  v2/internal/pkg/imagebuilder/interface.go
  v2/internal/pkg/imagebuilder/rebuild_catalog.go
  v2/internal/pkg/operator/filtered_collector.go
  v2/internal/pkg/spinners/spinners.go
Labels: approved, lgtm, jira/valid-reference

#956 CLID-278: Fix M2M of operator already built
  v2/internal/pkg/operator/filtered_collector.go
Labels: approved, lgtm, jira/valid-reference

#955 OCPBUGS-41331: Add an indicator in the log that catalog is mirrored t…
  v2/internal/pkg/batch/concurrent_worker.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#957 OCPBUGS-41331: Revert to arrow emoji when logging
  v2/internal/pkg/batch/concurrent_worker.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only

#958 CLID-279: removes the tech preview warning from v2
  v2/pkg/cli/cli_wrapper.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#962 OCPBUGS-44789: Fix mirroring OCI catalogs multiple times
  v2/internal/pkg/operator/filtered_collector.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#966 OCPBUGS-42862: oc-mirror fails to find the image-references
  v2/internal/pkg/cli/executor.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#963 OCPBUGS-44818: Fix mirroring catalogs with full:true
  v2/internal/pkg/api/v2alpha1/type_internal.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/operator/filtered_collector.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference
