Repository openshift/oc-mirror, pull requests merged in 2024-12, with the labels that each got.

#959 OCPBUGS-43731,OCPBUGS-44836:Ability to generate delete-images.yaml with v1 tags
  go.work.sum
  v2/go.mod
  v2/go.sum
  v2/internal/pkg/additional/local_stored_collector.go
  v2/internal/pkg/additional/local_stored_collector_test.go
  v2/internal/pkg/cli/delete.go
  v2/internal/pkg/cli/delete_test.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/helm/local_stored_collector.go
  v2/internal/pkg/helm/local_stored_collector_test.go
  v2/internal/pkg/operator/catalog_handler_test.go
  v2/internal/pkg/operator/common.go
  v2/internal/pkg/operator/common_test.go
  v2/internal/pkg/operator/filtered_collector.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only

#968 OCPBUGS-44448: Skip deletion of images with same source and different…
  v2/internal/pkg/batch/concurrent_worker.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#969 OCPBUGS-43275: De-duplicate release images when several releases are …
  v2/internal/pkg/release/local_stored_collector.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#967 OCPBUGS-44449: Fix batch info log for delete scenario
  v2/internal/pkg/batch/concurrent_worker.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#978 OCPBUGS-44033: Failed to mirror ocp payload using digest
  v2/internal/pkg/release/local_stored_collector.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#982 OCPBUGS-43825: Fix graph image not deletable if mirrored by m2m
  v2/internal/pkg/mirror/options.go
  v2/internal/pkg/release/local_stored_collector.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#979 OCPBUGS-42849: Assign a static name to the release signature configmap
  v2/internal/pkg/clusterresources/clusterresources.go
  v2/internal/pkg/clusterresources/clusterresources_test.go
  v2/internal/pkg/clusterresources/const.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only

#981 OCPBUGS-44901: Align tag format for additionalImages and operators
  v2/internal/pkg/additional/local_stored_collector.go
  v2/internal/pkg/additional/local_stored_collector_test.go
  v2/internal/pkg/operator/common.go
  v2/internal/pkg/operator/common_test.go
  v2/internal/pkg/operator/filtered_collector_test.go
  v2/internal/pkg/operator/local_stored_collector_test.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference

#986 NO-JIRA: Updating oc-mirror-plugin-container image to be consistent with ART for 4.19
  go.mod
  go.work
  images/cli/Dockerfile.ci
  v2/go.mod
Labels: approved, lgtm, jira/valid-reference

#990 OCPBUGS-45580: Fix Mirror2Disk not including the rebuilt catalog in t…
  v2/internal/pkg/cli/executor.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only

#988 OCPBUGS-43489: Fix for deleting of local cache using --force-cache-de…
  v2/internal/pkg/batch/concurrent_worker.go
  v2/internal/pkg/cli/delete.go
  v2/internal/pkg/delete/delete_images.go
  v2/internal/pkg/delete/delete_images_test.go
  v2/tests/delete/delete-images.yaml
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only
