Repository openshift/oc-mirror, pull requests merged in 2024-07, with the labels that each got.

#882 OCPBUGS-36214: Fix V2 DiskToMirror should not require internet access
  v2/internal/pkg/operator/local_stored_collector.go
  v2/internal/pkg/operator/local_stored_collector_test.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/operator/local_stored_collector.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#880 CLID-55: Improve Batch mechanism - ConcurrentWorker implementation
  v2/docs/progress-bar-and-concurrencty-investigation.md
  v2/go.mod
  v2/go.sum
  v2/internal/pkg/batch/concurrent_worker.go
  v2/internal/pkg/batch/concurrent_worker_test.go
  v2/internal/pkg/batch/const.go
  v2/internal/pkg/batch/interface.go
  v2/internal/pkg/batch/worker.go
  v2/internal/pkg/cli/const.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/cli/executor_test.go
  v2/vendor/github.com/stretchr/objx/.codeclimate.yml
  v2/vendor/github.com/stretchr/objx/.gitignore
  v2/vendor/github.com/stretchr/objx/LICENSE
  v2/vendor/github.com/stretchr/objx/README.md
  v2/vendor/github.com/stretchr/objx/Taskfile.yml
  v2/vendor/github.com/stretchr/objx/accessors.go
  v2/vendor/github.com/stretchr/objx/conversions.go
  v2/vendor/github.com/stretchr/objx/doc.go
  v2/vendor/github.com/stretchr/objx/map.go
  v2/vendor/github.com/stretchr/objx/mutations.go
  v2/vendor/github.com/stretchr/objx/security.go
  v2/vendor/github.com/stretchr/objx/tests.go
  v2/vendor/github.com/stretchr/objx/type_specific.go
  v2/vendor/github.com/stretchr/objx/type_specific_codegen.go
  v2/vendor/github.com/stretchr/objx/value.go
  v2/vendor/github.com/stretchr/testify/mock/doc.go
  v2/vendor/github.com/stretchr/testify/mock/mock.go
  v2/vendor/modules.txt
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/batch/concurrent_worker.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/batch/const.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/batch/interface.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/batch/worker.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/const.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/executor.go
Labels: approved, lgtm, jira/valid-reference

#883 CLID-99: consolidates the release collector for delete feature
  v2/docs/delete-functionality.md
  v2/internal/pkg/additional/local_stored_collector.go
  v2/internal/pkg/api/v2alpha1/type_internal.go
  v2/internal/pkg/archive/archive_test.go
  v2/internal/pkg/cli/const.go
  v2/internal/pkg/cli/delete.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/cli/executor_test.go
  v2/internal/pkg/cli/mock-delete.go
  v2/internal/pkg/delete/delete_images.go
  v2/internal/pkg/delete/delete_images_test.go
  v2/internal/pkg/delete/interface.go
  v2/internal/pkg/mirror/const.go
  v2/internal/pkg/mirror/options.go
  v2/internal/pkg/operator/local_stored_collector.go
  v2/internal/pkg/release/cincinnati.go
  v2/internal/pkg/release/client.go
  v2/internal/pkg/release/const.go
  v2/internal/pkg/release/core-cincinnati.go
  v2/internal/pkg/release/core-cincinnati_test.go
  v2/internal/pkg/release/graph.go
  v2/internal/pkg/release/interface.go
  v2/internal/pkg/release/local_stored_collector.go
  v2/internal/pkg/release/local_stored_collector_test.go
  v2/pkg/cli/cli_wrapper.go
  v2/tests/working-dir-fake/hold-release/cincinnati-graph-data/amd64-stable-4.13.json
  v2/tests/working-dir-fake/release-filters/690d64d2ebd41f1834c80e632f041b5b
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/additional/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/api/v2alpha1/type_internal.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/const.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/delete.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/mock-delete.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/delete/delete_images.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/delete/interface.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/mirror/const.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/mirror/options.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/operator/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/cincinnati.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/client.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/const.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/core-cincinnati.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/graph.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/interface.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/cli/cli_wrapper.go
Labels: approved, lgtm, jira/valid-reference

#885 OCPBUGS-36445: Fix to ensure invalid catalogs are skipped
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/manifest/oci-manifest.go
  v2/internal/pkg/operator/local_stored_collector.go
  v2/sonar-project.properties
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/manifest/oci-manifest.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/operator/local_stored_collector.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#888 OCPBUGS-36548: Skip catalogs that are non existing
  v2/internal/pkg/manifest/oci-manifest.go
  v2/internal/pkg/operator/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/manifest/oci-manifest.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/operator/local_stored_collector.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#889 [release-4.16] OCPBUGS-36498: Fix to ensure invalid catalogs are skipped
  v2/internal/pkg/additional/local_stored_collector.go
  v2/internal/pkg/batch/worker.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/manifest/oci-manifest.go
  v2/internal/pkg/operator/local_stored_collector.go
  v2/sonar-project.properties
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/additional/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/batch/worker.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/manifest/oci-manifest.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/operator/local_stored_collector.go
Labels: backport-risk-assessed, approved, cherry-pick-approved, qe-approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#891 OCPBUGS-37055: Use proxy for HTTP request release signatures
  v2/internal/pkg/release/signature.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/signature.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#892 [release-4.16] OCPBUGS-37040: use current working-dir for fetching release content f…
  v2/internal/pkg/release/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/local_stored_collector.go
Labels: backport-risk-assessed, approved, cherry-pick-approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#894 [v2] CLID-136: Skip deletion of operator catalog image in delete feature
  v2/internal/pkg/operator/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/operator/local_stored_collector.go
Labels: approved, lgtm, jira/valid-reference

#898 [v2] OCPBUGS-36410: fix: creates tags for release images
  v2/internal/pkg/release/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/local_stored_collector.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#895 [v2] CLID-133,CLID-98: feat: show operator on error logs and skip bundle when related image associated failed
  v2/internal/pkg/additional/local_stored_collector_test.go
  v2/internal/pkg/api/v2alpha1/type_image.go
  v2/internal/pkg/api/v2alpha1/type_internal.go
  v2/internal/pkg/batch/concurrent_worker.go
  v2/internal/pkg/batch/concurrent_worker_test.go
  v2/internal/pkg/batch/type.go
  v2/internal/pkg/batch/worker.go
  v2/internal/pkg/cli/delete.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/cli/executor_test.go
  v2/internal/pkg/delete/delete_images_test.go
  v2/internal/pkg/manifest/interface.go
  v2/internal/pkg/manifest/oci-manifest.go
  v2/internal/pkg/manifest/oci-manifest_test.go
  v2/internal/pkg/operator/interface.go
  v2/internal/pkg/operator/local_stored_collector.go
  v2/internal/pkg/operator/local_stored_collector_test.go
  v2/internal/pkg/operator/sort.go
  v2/internal/pkg/operator/sort_test.go
  v2/internal/pkg/release/local_stored_collector_test.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/api/v2alpha1/type_image.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/api/v2alpha1/type_internal.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/batch/concurrent_worker.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/batch/type.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/batch/worker.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/delete.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/manifest/interface.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/manifest/oci-manifest.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/operator/interface.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/operator/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/operator/sort.go
Labels: approved, lgtm, jira/valid-reference
