Repository openshift/oc-mirror, pull requests merged in 2024-04, with the labels that each got.

#817 OCPBUGS-31084: feat: retro-compatible version cmd with v1
  Makefile
  v2/pkg/cli/executor.go
  v2/pkg/version/version.go
  v2/pkg/version/version_test.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/version/version.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#820 OCPBUGS-31344: fix: issue when different versions of the same catalog
  v2/pkg/additional/local_stored_collector_test.go
  v2/pkg/batch/worker_test.go
  v2/pkg/manifest/interface.go
  v2/pkg/manifest/oci-manifest.go
  v2/pkg/operator/local_stored_collector.go
  v2/pkg/operator/local_stored_collector_test.go
  v2/pkg/release/local_stored_collector_test.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/manifest/interface.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/manifest/oci-manifest.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/operator/local_stored_collector.go
Labels: approved, do-not-merge/hold, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#816 OCPBUGS-31024: Ommit icon from catalogSource if empty
  v2/pkg/api/operator-framework/v1alpha1/catalogsource_types.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/api/operator-framework/v1alpha1/catalogsource_types.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#811 CLID-54: Mirror to mirror workflow
  Makefile
  docs/enclave_support.md
  v2/Makefile
  v2/pkg/additional/local_stored_collector.go
  v2/pkg/cli/additional_integration_test.go
  v2/pkg/cli/executor.go
  v2/pkg/cli/executor_test.go
  v2/pkg/cli/release_integration_test.go
  v2/pkg/mirror/const.go
  v2/pkg/mirror/options.go
  v2/pkg/operator/local_stored_collector.go
  v2/pkg/release/graph.go
  v2/pkg/release/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/additional/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/mirror/const.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/mirror/options.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/operator/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/graph.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/local_stored_collector.go
Labels: approved, lgtm, jira/valid-reference

#815 OCPBUGS-31466: Fix for oc-mirror new defaultChannel override
  pkg/operator/diff/internal/diff.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#828 CLID-85: Change string replacement in registry config to use templates
  v2/pkg/cli/executor.go
  v2/pkg/cli/executor_test.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
Labels: approved, lgtm, jira/valid-reference

#827 CLID-47,CLID-46: Use of TargetCatalog and TargetTag on all catalogs
  v2/pkg/additional/local_stored_collector.go
  v2/pkg/api/v1alpha2/types_config.go
  v2/pkg/api/v1alpha2/types_config_test.go
  v2/pkg/api/v1alpha3/types.go
  v2/pkg/clusterresources/clusterresources.go
  v2/pkg/config/validate_test.go
  v2/pkg/image/image.go
  v2/pkg/operator/local_stored_collector.go
  v2/pkg/operator/local_stored_collector_test.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/additional/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/api/v1alpha2/types_config.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/api/v1alpha3/types.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/clusterresources/clusterresources.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/image/image.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/operator/local_stored_collector.go
Labels: approved, lgtm, jira/valid-reference

#831 CLID-53: Introduce env var to provide OCP release signature verificat…
  v2/pkg/release/signature.go
  v2/pkg/release/signature_test.go
  v2/tests/buggy-ocp-sig-key.asc
  v2/tests/custom-ocp-sig-key.asc
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/signature.go
Labels: approved, lgtm, jira/valid-reference

#832 CLID-58,CLID-95,CLID-60: improvements on log output
  pkg/cli/mirror/mirror.go
  v2/pkg/additional/const.go
  v2/pkg/additional/local_stored_collector.go
  v2/pkg/api/v1alpha3/types.go
  v2/pkg/batch/const.go
  v2/pkg/batch/worker.go
  v2/pkg/batch/worker_test.go
  v2/pkg/cli/const.go
  v2/pkg/cli/delete.go
  v2/pkg/cli/executor.go
  v2/pkg/cli/executor_test.go
  v2/pkg/cli/prepare.go
  v2/pkg/clusterresources/clusterresources.go
  v2/pkg/delete/delete_images.go
  v2/pkg/delete/delete_images_test.go
  v2/pkg/manifest/oci-manifest.go
  v2/pkg/mirror/mirror.go
  v2/pkg/mirror/options.go
  v2/pkg/operator/const.go
  v2/pkg/operator/local_stored_collector.go
  v2/pkg/release/cincinnati.go
  v2/pkg/release/const.go
  v2/pkg/release/local_stored_collector.go
  v2/pkg/release/signature.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/additional/const.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/additional/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/api/v1alpha3/types.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/batch/const.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/batch/worker.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/cli/const.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/cli/delete.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/cli/prepare.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/clusterresources/clusterresources.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/delete/delete_images.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/manifest/oci-manifest.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/mirror/mirror.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/mirror/options.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/operator/const.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/operator/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/cincinnati.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/const.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/signature.go
Labels: approved, lgtm, jira/valid-reference

#836 CLID-66,CLID-81: refines v2 --help
  pkg/cli/mirror/mirror.go
  v2/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
Labels: approved, lgtm, jira/valid-reference

#834 CLID-53: Exit if release is unsigned
  v2/pkg/release/signature.go
  v2/pkg/release/signature_test.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/signature.go
Labels: approved, lgtm, jira/valid-reference

#837 CLID-66,CLID-80: changes README.md
  v2/README.md
  v2/docs/delete-functionality.md
  v2/docs/enclave_support.md
  v2/docs/operator-filtering-investigation.md
  v2/docs/progress-bar-and-concurrencty-investigation.md
  v2/docs/signature-verification.md
Labels: approved, lgtm, jira/valid-reference

#838 CLID-101: Fix TlsVerify always set to false
  v2/pkg/additional/local_stored_collector_test.go
  v2/pkg/archive/archive_test.go
  v2/pkg/archive/image-blob-gatherer.go
  v2/pkg/archive/image-blob-gatherer_test.go
  v2/pkg/batch/worker_test.go
  v2/pkg/cli/additional_integration_test.go
  v2/pkg/cli/delete.go
  v2/pkg/cli/delete_test.go
  v2/pkg/cli/dryrun_test.go
  v2/pkg/cli/executor.go
  v2/pkg/cli/executor_test.go
  v2/pkg/cli/release_integration_test.go
  v2/pkg/delete/delete_images_test.go
  v2/pkg/imagebuilder/builder.go
  v2/pkg/imagebuilder/builder_test.go
  v2/pkg/mirror/mirror_test.go
  v2/pkg/mirror/options.go
  v2/pkg/mirror/options_test.go
  v2/pkg/operator/local_stored_collector_test.go
  v2/pkg/release/cincinnati_test.go
  v2/pkg/release/graph_test.go
  v2/pkg/release/local_stored_collector_test.go
  v2/pkg/release/signature_test.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/archive/image-blob-gatherer.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/cli/delete.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/imagebuilder/builder.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/mirror/options.go
Labels: approved, lgtm, jira/valid-reference

#840 CLID-101: Fix graph image mirroring after TLS verification enabling
  v2/internal/pkg/batch/worker.go
  v2/internal/pkg/release/cincinnati.go
  v2/internal/pkg/release/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/batch/worker.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/cincinnati.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/local_stored_collector.go
Labels: approved, qe-approved, lgtm, jira/valid-reference

#841 OCPBUGS-31083: Fix help for --strict-archive flag
  v2/internal/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/executor.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#842 OCPBUGS-31092: Fix archive tar file size to respect the archiveSize s…
  v2/internal/pkg/archive/archive.go
  v2/internal/pkg/archive/permissive_adder_test.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/archive/archive.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference
