Repository openshift/oc-mirror, pull requests merged in 2024-09, with the labels that each got.

#916 OCPBUGS-37740: Should not panic when invalid log-level flag is used
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/cli/executor_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#918 OCPBUGS-41168: [release-4.17] Should not panic when specifying wrong …
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/cli/executor_test.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/executor.go
Labels: backport-risk-assessed, approved, cherry-pick-approved, qe-approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#920 OCPBUGS-37948,CLID-196: Fix deletion of operators mirrored in M2M
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/cli/executor_test.go
  v2/internal/pkg/operator/local_stored_collector.go
  v2/internal/pkg/operator/local_stored_collector_test.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#922 OCPBUGS-41503: [release-4.17] oc-mirror throws error when performing delete operation with --generate
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/cli/executor_test.go
  v2/internal/pkg/clusterresources/clusterresources.go
  v2/internal/pkg/clusterresources/clusterresources_test.go
  v2/internal/pkg/operator/local_stored_collector.go
  v2/internal/pkg/operator/local_stored_collector_test.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/clusterresources/clusterresources.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/operator/local_stored_collector.go
Labels: backport-risk-assessed, approved, cherry-pick-approved, qe-approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#921 CLID-160,OCPBUGS-36569: upgrading containers/image, oc and library-go
  Makefile
  go.mod
  go.sum
  go.work
  go.work.sum
  internal/testutils/testutils.go
  pkg/cincinnati/cincinnati.go
  pkg/cli/mirror/publish.go
  pkg/cli/mirror/release.go
  pkg/image/association_builder.go
  pkg/image/builder/image_builder.go
  pkg/image/convert.go
  pkg/metadata/storage/registry.go
  test/e2e/testcases.sh
  v2/go.mod
  v2/go.sum
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#928 NO-ISSUE: art build fix for the cachito issue
  go.mod
  go.sum
  v2/go.mod
  v2/go.sum
Labels: approved, lgtm, jira/valid-reference

#927 CLID-62,CLID-239: removes build-machinery-go from the oc-mirror root folder
  Makefile
  build-machinery-go/.ci-operator.yaml
  build-machinery-go/LICENSE
  build-machinery-go/Makefile
  build-machinery-go/OWNERS
  build-machinery-go/README.md
  build-machinery-go/doc.go
  build-machinery-go/make/default.example.mk
  build-machinery-go/make/default.example.mk.help.log
  build-machinery-go/make/default.mk
  build-machinery-go/make/doc.go
  build-machinery-go/make/golang.example.mk
  build-machinery-go/make/golang.example.mk.help.log
  build-machinery-go/make/golang.mk
  build-machinery-go/make/lib/doc.go
  build-machinery-go/make/lib/golang.mk
  build-machinery-go/make/lib/tmp.mk
  build-machinery-go/make/lib/version.mk
  build-machinery-go/make/operator.example.mk
  build-machinery-go/make/operator.example.mk.help.log
  build-machinery-go/make/operator.mk
  build-machinery-go/make/targets/doc.go
  build-machinery-go/make/targets/golang/build.mk
  build-machinery-go/make/targets/golang/doc.go
  build-machinery-go/make/targets/golang/test-unit.mk
  build-machinery-go/make/targets/golang/verify-update.mk
  build-machinery-go/make/targets/golang/version.mk
  build-machinery-go/make/targets/help.mk
  build-machinery-go/make/targets/openshift/bindata.mk
  build-machinery-go/make/targets/openshift/codegen.mk
  build-machinery-go/make/targets/openshift/controller-gen.mk
  build-machinery-go/make/targets/openshift/crd-schema-gen.mk
  build-machinery-go/make/targets/openshift/deps-glide.mk
  build-machinery-go/make/targets/openshift/deps-gomod.mk
  build-machinery-go/make/targets/openshift/deps.mk
  build-machinery-go/make/targets/openshift/doc.go
  build-machinery-go/make/targets/openshift/imagebuilder.mk
  build-machinery-go/make/targets/openshift/images.mk
  build-machinery-go/make/targets/openshift/kustomize.mk
  build-machinery-go/make/targets/openshift/operator/doc.go
  build-machinery-go/make/targets/openshift/operator/profile-manifests.mk
  build-machinery-go/make/targets/openshift/operator/release.mk
  build-machinery-go/make/targets/openshift/operator/telepresence.mk
  build-machinery-go/make/targets/openshift/rpm.mk
  build-machinery-go/make/targets/openshift/yaml-patch.mk
  build-machinery-go/make/targets/openshift/yq.mk
  build-machinery-go/scripts/doc.go
  build-machinery-go/scripts/run-telepresence.sh
  build-machinery-go/scripts/update-deps.sh
Labels: approved, lgtm, jira/valid-reference

#924 CLID-232,OCPBUGS-38339,OCPBUGS-38343,OCPBUGS-38233: Create release signature configmap
  go.work.sum
  v2/internal/pkg/api/kubernetes/core/type_configmap.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/cli/executor_test.go
  v2/internal/pkg/clusterresources/clusterresources.go
  v2/internal/pkg/clusterresources/clusterresources_test.go
  v2/internal/pkg/clusterresources/const.go
  v2/internal/pkg/clusterresources/interface.go
  v2/internal/pkg/release/cincinnati.go
  v2/internal/pkg/release/signature.go
  v2/internal/pkg/release/signature_test.go
  v2/internal/pkg/release/test-arch-empty-4.0.json
  v2/internal/pkg/release/test-arch-stable-4.0.json
  v2/tests/37433b71c073c6cbfc8173ec7ab2d99032c8e6d6fe29de06e062d85e33e34531
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#931 OCPBUGS-42416: Only generate release config map when releases are sp…
  v2/internal/pkg/clusterresources/clusterresources.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#933 OCPBUGS-38461: oc-mirror should fail when the cincinnati API has errors
  go.work.sum
  v2/internal/pkg/release/cincinnati.go
  v2/internal/pkg/release/cincinnati_test.go
  v2/internal/pkg/release/interface.go
  v2/internal/pkg/release/local_stored_collector.go
  v2/internal/pkg/release/local_stored_collector_test.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference
