Repository openshift/oc-mirror, pull requests merged in 2024-05, with the labels that each got.

#843 OCPBUGS-33098: fix: generates a file with errors during mirroring
  v2/internal/pkg/batch/worker.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/batch/worker.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#844 OCPBUGS-31536: Change default behavior to not rebuild catalogs for V1
  pkg/cli/mirror/catalog_images.go
  pkg/cli/mirror/fbc_operators.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/operator.go
  pkg/cli/mirror/options.go
  pkg/cli/mirror/publish.go
  test/e2e/lib/workflow.sh
  test/e2e/testcases.sh
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#847 OCPBUGS-31536: Change default behavior to not rebuild catalogs for V1 - 2
  pkg/cli/mirror/catalog_images.go
  pkg/cli/mirror/fbc_operators.go
  pkg/cli/mirror/mirror.go
  pkg/cli/mirror/operator.go
  pkg/cli/mirror/publish.go
  test/e2e/testcases.sh
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#848 OCPBUGS-32547: Fix delete generation for mirror to mirror flow
  v2/docs/delete-functionality.md
  v2/internal/pkg/batch/worker.go
  v2/internal/pkg/cli/const.go
  v2/internal/pkg/cli/delete.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/delete/delete_images.go
  v2/internal/pkg/log/logger.go
  v2/internal/pkg/mirror/mirror.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/batch/worker.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/const.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/delete.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/delete/delete_images.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/log/logger.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/mirror/mirror.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#852 OCPBUGS-31536:OCPBUGS-33554: Fix mirroring operators on fedora systems - no sig verification
  pkg/cli/mirror/fbc_operators.go
  pkg/cli/mirror/options.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#851 OCPBUGS-31622: Fix operator related image has empty reference
  v2/internal/pkg/operator/local_stored_collector.go
  v2/internal/pkg/operator/local_stored_collector_test.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/operator/local_stored_collector.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#850 OCPBUGS-31608:OCPBUGS-33775: Fix source repository for IDMS/ITMS in case of empty namespace
  v2/internal/pkg/additional/local_stored_collector_test.go
  v2/internal/pkg/batch/worker_test.go
  v2/internal/pkg/cli/const.go
  v2/internal/pkg/cli/dryrun.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/cli/executor_test.go
  v2/internal/pkg/clusterresources/clusterresources.go
  v2/internal/pkg/clusterresources/clusterresources_test.go
  v2/internal/pkg/mirror/mirror.go
  v2/internal/pkg/mirror/mirror_test.go
  v2/internal/pkg/operator/local_stored_collector_test.go
  v2/internal/pkg/release/local_stored_collector_test.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/const.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/dryrun.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/clusterresources/clusterresources.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/mirror/mirror.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#858 OCPBUGS-34021: Activate flags for timeout, retry and maxParallelDownload
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/mirror/options.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/mirror/options.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#856 OCPBUGS-33580: Fix shortestPath returning 3 times the same imageSet
  v2/internal/pkg/release/cincinnati.go
  vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/cincinnati.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#862 OCPBUGS-34521: Fix DiskToMirror without internet connection without r…
  pkg/cli/mirror/catalog_images.go
  pkg/cli/mirror/operator.go
  pkg/image/builder/image_builder.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#859 OCPBUGS-34211: docker.io registry/2 is pulled with a platform argument
  test/e2e/lib/util.sh
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference
