Repository openshift/oc-mirror, pull requests merged in 2024-03, with the labels that each got.

#800 CLID-27: Update to include oci (disk based layout) for v2
  v2/asciinema.txt
  v2/pkg/api/v1alpha3/types.go
  v2/pkg/operator/const.go
  v2/pkg/operator/local_stored_collector.go
  v2/pkg/operator/local_stored_collector_test.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/api/v1alpha3/types.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/operator/const.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/operator/local_stored_collector.go
Labels: approved, lgtm, jira/valid-reference

#807 CLID-70: fix: issue when mirroring multiple catalogs
  v2/pkg/image/image.go
  v2/pkg/operator/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/image/image.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/operator/local_stored_collector.go
Labels: approved, lgtm, jira/valid-reference

#804 OCPBUGS-25346: Generate both oc-mirror binaries for rhel9 and rhel8
  .ci-operator.yaml
  images/cli/Dockerfile.ci
Labels: backport-risk-assessed, approved, cherry-pick-approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#810 CLID-17: feat: docker v2s2 manifest list / oci image index implementation
  v2/pkg/additional/const.go
  v2/pkg/additional/local_stored_collector.go
  v2/pkg/additional/local_stored_collector_test.go
  v2/pkg/api/v1alpha3/types.go
  v2/pkg/batch/worker.go
  v2/pkg/batch/worker_test.go
  v2/pkg/cli/executor.go
  v2/pkg/cli/executor_test.go
  v2/pkg/manifest/interface.go
  v2/pkg/manifest/oci-manifest.go
  v2/pkg/operator/local_stored_collector.go
  v2/pkg/operator/local_stored_collector_test.go
  v2/pkg/release/local_stored_collector_test.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/additional/const.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/additional/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/api/v1alpha3/types.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/batch/worker.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/manifest/interface.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/manifest/oci-manifest.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/operator/local_stored_collector.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#798 CLID-8: Initial E2E test for v2
  Makefile
  v2/Makefile
  v2/internal/e2e/signatures/signature-1
  v2/internal/e2e/templates/isc_templates/additional_isc.yaml
  v2/internal/e2e/templates/isc_templates/release_isc.yaml
  v2/internal/e2e/templates/regisitries.conf
  v2/internal/e2e/templates/release_templates/cincinnati_stable-4.0.json
  v2/internal/e2e/templates/release_templates/cincinnati_stable-4.15.json
  v2/internal/e2e/templates/release_templates/image-references
  v2/internal/e2e/templates/release_templates/release-metadata
  v2/internal/testutils/testutils.go
  v2/pkg/additional/local_stored_collector.go
  v2/pkg/additional/local_stored_collector_test.go
  v2/pkg/archive/image-blob-gatherer_test.go
  v2/pkg/batch/worker.go
  v2/pkg/batch/worker_test.go
  v2/pkg/cli/additional_integration_test.go
  v2/pkg/cli/executor.go
  v2/pkg/cli/executor_test.go
  v2/pkg/cli/release_integration_test.go
  v2/pkg/imagebuilder/builder_test.go
  v2/pkg/manifest/oci-manifest.go
  v2/pkg/mirror/mirror.go
  v2/pkg/mirror/mirror_test.go
  v2/pkg/mirror/options.go
  v2/pkg/operator/local_stored_collector.go
  v2/pkg/operator/local_stored_collector_test.go
  v2/pkg/release/cincinnati.go
  v2/pkg/release/local_stored_collector.go
  v2/pkg/release/local_stored_collector_test.go
  v2/pkg/release/signature.go
  v2/pkg/release/signature_test.go
  v2/vendor/github.com/stretchr/testify/suite/doc.go
  v2/vendor/github.com/stretchr/testify/suite/interfaces.go
  v2/vendor/github.com/stretchr/testify/suite/stats.go
  v2/vendor/github.com/stretchr/testify/suite/suite.go
  v2/vendor/modules.txt
  vendor/github.com/openshift/oc-mirror/v2/pkg/additional/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/batch/worker.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/manifest/oci-manifest.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/mirror/mirror.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/mirror/options.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/operator/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/cincinnati.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/local_stored_collector.go
  vendor/github.com/openshift/oc-mirror/v2/pkg/release/signature.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only
