Repository openshift/oc-mirror, pull requests merged in 2025-03, with the labels that each got.

#1101 [release-4.18] OCPBUGS-51386: fixes CVE-2024-0406
  go.mod
  go.sum
  go.work.sum
Labels: backport-risk-assessed, approved, cherry-pick-approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#1100 CLID-325: adds cpu and memory profiling / removes the race from build target
  Makefile
  cmd/oc-mirror/main.go
  v2/hack/run_and_pprof.sh
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/mirror/options.go
Labels: approved, lgtm, jira/valid-reference

#1097 OCPBUGS-51328: Fix CVE-2025-27144
  go.mod
  go.sum
  go.work.sum
  v2/go.mod
  v2/go.sum
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1104 no-jira: stop `wraperr` linter from treating our code as external lib
  v2/.golangci.yaml
Labels: approved, lgtm, jira/valid-reference

#1098 no-jira: v2/manifest/oci-manifest: refactor and dedup the code
  v2/go.mod
  v2/internal/pkg/clusterresources/clusterresources.go
  v2/internal/pkg/clusterresources/clusterresources_test.go
  v2/internal/pkg/delete/delete_images.go
  v2/internal/pkg/helm/local_stored_collector.go
  v2/internal/pkg/manifest/oci-manifest.go
  v2/internal/pkg/manifest/oci-manifest_test.go
  v2/internal/pkg/operator/local_stored_collector_test.go
  v2/internal/pkg/parser/parse.go
  v2/internal/pkg/parser/parse_test.go
  v2/internal/pkg/release/core-cincinnati.go
  v2/internal/pkg/release/local_stored_collector.go
  v2/internal/pkg/release/signature.go
Labels: approved, lgtm, jira/valid-reference

#1093 OCPBUGS-50680: v2/operator: refactor operator FilteredCollector
  v2/internal/pkg/api/v2alpha1/type_internal.go
  v2/internal/pkg/operator/common.go
  v2/internal/pkg/operator/common_test.go
  v2/internal/pkg/operator/filtered_collector.go
  v2/internal/pkg/operator/filtered_collector_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1105 OCPBUGS-52588: fix: error when no related image was found
  v2/internal/pkg/operator/catalog_handler.go
  v2/internal/pkg/operator/catalog_handler_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1110 OCPBUGS-52969: remove TechPreview mentions of v2 in --help
  pkg/cli/mirror/options.go
  v2/internal/pkg/cli/executor.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#1115 OCPBUGS-52978: delete: fix typo in --help output
  v2/internal/pkg/cli/delete.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1109 OCPBUGS-52960: v2: fix setting version during build
  Makefile
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference
