Repository openshift/oc-mirror, pull requests merged in 2025-05, with the labels that each got.

#1129 OCPBUGS-54220: v2/imgbuilder: use --authfile when set
  go.work.sum
  v2/go.mod
  v2/internal/pkg/imagebuilder/builder.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#1131 OCPBUGS-55100: implements registries.d file as specified in containers/image docs
  v2/internal/pkg/api/v2alpha1/type_internal.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/registriesd/error.go
  v2/internal/pkg/registriesd/registriesd.go
  v2/internal/pkg/registriesd/types.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1078 no-jira: Disable go workspace and build v2 as a binary
  .gitignore
  Makefile
  cmd/oc-mirror/data/README
  cmd/oc-mirror/main.go
  go.sum
  go.work
  go.work.sum
  images/cli/Dockerfile.test
  pkg/cli/mirror/mirror.go
  v2/Makefile
  v2/cmd/oc-mirror/main.go
  v2/go.mod
  v2/go.sum
  v2/internal/pkg/cli/executor.go
  v2/pkg/cli/cli_wrapper.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#1125 OCPBUGS-54626: [release-4.18] cli: return distinct error codes depending on failure
  v2/go.mod
  v2/internal/pkg/batch/common.go
  v2/internal/pkg/batch/concurrent_chan_worker.go
  v2/internal/pkg/batch/concurrent_worker.go
  v2/internal/pkg/batch/concurrent_worker_test.go
  v2/internal/pkg/batch/error.go
  v2/internal/pkg/batch/new.go
  v2/internal/pkg/cli/delete.go
  v2/internal/pkg/cli/error.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/cli/executor_test.go
  v2/internal/pkg/delete/delete_images.go
  v2/internal/pkg/errcode/code.go
  v2/internal/pkg/release/local_stored_collector.go
Labels: backport-risk-assessed, approved, cherry-pick-approved, lgtm, jira/valid-bug, jira/valid-reference

#1085 CLID-182: Add spinner to release collector mirror to disk or mirror t…
  v2/internal/pkg/batch/concurrent_chan_worker.go
  v2/internal/pkg/operator/filtered_collector.go
  v2/internal/pkg/release/local_stored_collector.go
  v2/internal/pkg/spinners/spinners.go
Labels: approved, lgtm, jira/valid-reference

#1138 OCPBUGS-54587: v2: bump containers/common dep to 0.63.0
  v2/go.mod
  v2/go.sum
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1143 OCPBUGS-56088: changes the signature mirroring default to disabled
  v2/internal/pkg/cli/executor.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#1145 OCPBUGS-56117: Make v2 blockedImages use regular expressions
  v2/internal/pkg/cli/executor.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1144 OCPBUGS-54443: v2/cli: always remove past archives before m2d
  v2/internal/pkg/archive/archive.go
  v2/internal/pkg/archive/archive_test.go
  v2/internal/pkg/cli/executor.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#1141 OCPBUGS-55966: v2/archive: print unarchive progress
  v2/internal/pkg/archive/unarchive.go
  v2/internal/pkg/archive/unarchive_test.go
  v2/internal/pkg/cli/executor.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#1151 OCPBUGS-56378: disables the signature verification on operator catalog collection
  v2/internal/pkg/operator/filtered_collector.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#1159 OCPBUGS-56642: update the Dockerfile to work with the 1.23 go.mod
  Dockerfile
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1164 OCPBUGS-56486: v2/config: allow `delete` and `mirror` words
  v2/internal/pkg/config/load.go
  v2/internal/pkg/config/load_test.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#1147 OCPBUGS-56009: Bug fix for no release signature found
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/mirror/options.go
  v2/internal/pkg/release/signature.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference
