Repository openshift/oc-mirror, pull requests merged in 2025-02, with the labels that each got.

#1058 OCPBUGS-49723: v2/clusterresources: remove ClusterCatalog namespace
  v2/internal/pkg/clusterresources/clusterresources.go
  v2/internal/pkg/clusterresources/clusterresources_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference, acknowledge-critical-fixes-only

#1060 OCPBUGS-49730: fixes the infinite loop when no images to mirror
  v2/internal/pkg/batch/concurrent_chan_worker.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/emoji/const.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#1063 OCPBUGS-49798: exposes the parallel-layers flag
  v2/internal/pkg/cli/executor.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1043 OCPBUGS-49803: v2/cli: share common flag options
  v2/internal/pkg/cli/const.go
  v2/internal/pkg/cli/delete.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/mirror/options.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1069 NO-JIRA: only save graph data if it's valid json
  v2/internal/pkg/release/core-cincinnati.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#1071 OCPBUGS-49991: fixes bundle related images being skipped
  v2/internal/pkg/operator/catalog_handler.go
  v2/internal/pkg/operator/filtered_collector.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1072 OCPBUGS-50503: oc-mirror fails with error `unknown image: reference n…
  v2/internal/pkg/release/local_stored_collector.go
Labels: approved, cherry-pick-approved, qe-approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#1049 OCPBUGS-50559: v2: disable spinners when not running in a tty
  v2/go.mod
  v2/internal/pkg/batch/concurrent_chan_worker.go
  v2/internal/pkg/batch/concurrent_worker.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/mirror/options.go
  v2/internal/pkg/operator/filtered_collector.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1077 OCPBUGS-50685: fix: make the spinner trigger after semaphore is released
  v2/internal/pkg/batch/concurrent_chan_worker.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#1070 OCPBUGS-49990: v2/release: error out for kubevirt/graph image errors
  v2/internal/pkg/archive/archive_test.go
  v2/internal/pkg/release/local_stored_collector.go
  v2/tests/working-dir-fake/hold-release/ocp-release/v4.13.10/release-manifests/0000_50_installer_coreos-bootimages.yaml
  v2/tests/working-dir-fake/hold-release/ocp-release/v4.13.9/release-manifests/0000_50_installer_coreos-bootimages.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1080 OCPBUGS-44103: bump oc fork version
  go.mod
  go.sum
  go.work.sum
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only

#1087 OCPBUGS-50963: v2: don't clean cluster resources on dry-run mode
  v2/internal/pkg/cli/executor.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#1083 no-jira: v2: update golangci-lint config
  v2/.golangci.yaml
Labels: approved, lgtm, jira/valid-reference

#1081 OCPBUGS-50981: [release-4.18] v2/release: error out for kubevirt/graph image errors
  v2/internal/pkg/archive/archive_test.go
  v2/internal/pkg/release/local_stored_collector.go
  v2/tests/working-dir-fake/hold-release/ocp-release/v4.13.10/release-manifests/0000_50_installer_coreos-bootimages.yaml
  v2/tests/working-dir-fake/hold-release/ocp-release/v4.13.9/release-manifests/0000_50_installer_coreos-bootimages.yaml
Labels: backport-risk-assessed, approved, cherry-pick-approved, lgtm, jira/valid-bug, jira/valid-reference

#1082 OCPBUGS-50996: [release-4.18] v2: disable spinners when not running in a tty
  go.mod
  go.sum
  go.work.sum
  v2/go.mod
  v2/go.sum
  v2/internal/pkg/batch/concurrent_chan_worker.go
  v2/internal/pkg/batch/concurrent_worker.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/mirror/options.go
  v2/internal/pkg/operator/filtered_collector.go
Labels: backport-risk-assessed, approved, cherry-pick-approved, lgtm, jira/valid-bug, jira/valid-reference

#1092 CLID-203,OCPBUGS-26771: fixes CVE-2024-0406
  go.mod
  go.sum
  go.work.sum
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference
