Repository openshift/oc-mirror, pull requests merged in 2025-01, with the labels that each got.

#994 [release-4.18] OCPBUGS-45249: Failed to mirror ocp payload using digest
  v2/internal/pkg/release/local_stored_collector.go
Labels: backport-risk-assessed, approved, cherry-pick-approved, qe-approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#995 OCPBUGS-45215: cli: fix log level validation
  v2/internal/pkg/cli/executor.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference

#996 no-jira: make: also fmt/vet the v2 module
  Makefile
Labels: approved, lgtm, jira/valid-reference

#997 OCPBUGS-47453: Use a newer sha256 key to verify release signatures
  pkg/cli/mirror/release-configmap.yaml
  v2/internal/pkg/release/cincinnati.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference, acknowledge-critical-fixes-only

#1004 OCPBUGS-44714: don't clear cluster-resources dir on `delete --generate`
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/cli/executor_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1007 no-jira: OWNERS: add myself to reviewers.
  OWNERS
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#960 OCPBUGS-44799,CLID-181,CLID-204: new concurrent worker using channels
  Makefile
  go.mod
  go.sum
  go.work.sum
  v2/go.mod
  v2/go.sum
  v2/internal/pkg/api/v2alpha1/type_image.go
  v2/internal/pkg/batch/common.go
  v2/internal/pkg/batch/concurrent_chan_worker.go
  v2/internal/pkg/batch/concurrent_worker.go
  v2/internal/pkg/batch/concurrent_worker_test.go
  v2/internal/pkg/batch/const.go
  v2/internal/pkg/batch/new.go
  v2/internal/pkg/batch/type.go
  v2/internal/pkg/batch/worker.go
  v2/internal/pkg/batch/worker_test.go
  v2/internal/pkg/cli/additional_integration_test.go
  v2/internal/pkg/cli/delete.go
  v2/internal/pkg/cli/dryrun.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/cli/executor_test.go
  v2/internal/pkg/cli/release_integration_test.go
  v2/internal/pkg/clusterresources/clusterresources.go
  v2/internal/pkg/customsort/sort.go
  v2/internal/pkg/customsort/sort_test.go
  v2/internal/pkg/delete/delete_images.go
  v2/internal/pkg/emoji/const.go
  v2/internal/pkg/imagebuilder/rebuild_catalog.go
  v2/internal/pkg/mirror/mirror.go
  v2/internal/pkg/mirror/options.go
  v2/internal/pkg/operator/filtered_collector.go
  v2/internal/pkg/operator/local_stored_collector.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1020 OCPBUGS-48537: [release-4.17] e2e: use same version of crane as in go.mod
  test/e2e/lib/util.sh
Labels: backport-risk-assessed, approved, cherry-pick-approved, lgtm, jira/valid-bug, jira/valid-reference

#1017 OCPBUGS-48543: [release-4.17] changes the owners file
  OWNERS
Labels: backport-risk-assessed, approved, cherry-pick-approved, lgtm, jira/valid-bug, jira/valid-reference

#1018 OCPBUGS-48539: [release-4.18] changes the owners file
  OWNERS
Labels: backport-risk-assessed, approved, cherry-pick-approved, lgtm, jira/valid-bug, jira/valid-reference

#1015 OCPBUGS-48544: [release-4.16] changes the owners file
  OWNERS
Labels: backport-risk-assessed, approved, cherry-pick-approved, lgtm, jira/valid-bug, jira/valid-reference

#1014 OCPBUGS-48545: [release-4.15] changes the owners file
  OWNERS
Labels: backport-risk-assessed, approved, cherry-pick-approved, lgtm, jira/valid-bug, jira/valid-reference

#1013 OCPBUGS-48546: [release-4.14] changes the owners file
  OWNERS
Labels: backport-risk-assessed, approved, cherry-pick-approved, lgtm, jira/valid-bug, jira/valid-reference

#1025 OCPBUGS-48559: [release-4.13] e2e: use same version of crane as in go.mod
  test/e2e/lib/util.sh
Labels: backport-risk-assessed, approved, cherry-pick-approved, lgtm, jira/valid-bug, jira/valid-reference

#1002 OCPBUGS-47688: Fix ITMS and IDMS generated when mirror dest contains …
  v2/internal/pkg/clusterresources/clusterresources.go
  v2/internal/pkg/clusterresources/clusterresources_test.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference, acknowledge-critical-fixes-only

#1012 OCPBUGS-48547: [release-4.13] changes the owners file
  OWNERS
Labels: backport-risk-assessed, approved, cherry-pick-approved, lgtm, jira/valid-bug, jira/valid-reference

#1011 OCPBUGS-48549: [release-4.12] changes the owners file
  OWNERS
Labels: backport-risk-assessed, approved, cherry-pick-approved, lgtm, jira/valid-bug, jira/valid-reference

#1028 OCPBUGS-48602,OCPBUGS-48603: fixes CVEs upgrading go-git dependency
  go.mod
  go.sum
  go.work.sum
  v2/go.mod
  v2/go.sum
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#1029 [release-4.18] OCPBUGS-47816,OCPBUGS-47935: fixes CVEs upgrading go-git dependency
  go.mod
  go.sum
  go.work.sum
  v2/go.mod
  v2/go.sum
Labels: backport-risk-assessed, approved, cherry-pick-approved, qe-approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#1034 OCPBUGS-45161: Generate ClusterCatalog resources for operator catalogs
  v2/internal/pkg/api/operator-framework/v1/clustercatalog_types.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/cli/executor_test.go
  v2/internal/pkg/clusterresources/clusterresources.go
  v2/internal/pkg/clusterresources/clusterresources_test.go
  v2/internal/pkg/clusterresources/interface.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1035 CLID-301: add --cache-dir command line option
  v2/docs/delete-functionality.md
  v2/internal/pkg/cli/delete_test.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/cli/executor_test.go
  v2/internal/pkg/mirror/options.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#1036 OCPBUGS-45059: fixes the delete when catalog mirrored with v1 from disk (oci://)
  v2/internal/pkg/api/v2alpha1/type_internal.go
  v2/internal/pkg/operator/common.go
  v2/internal/pkg/operator/filtered_collector.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1041 CLID-301: add --cache-dir to delete command
  v2/internal/pkg/cli/delete.go
  v2/internal/pkg/cli/executor.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#1045 CLID-303: disables the selected bundle feature
  docs/design/imageset-configuration.md
  docs/examples/imageset-config-filter-catalog-by-bundle.yaml
  v2/docs/operator-filtering-investigation.md
  v2/internal/pkg/api/v2alpha1/type_config_include.go
  v2/internal/pkg/config/validate.go
  v2/internal/pkg/config/validate_test.go
  v2/internal/pkg/operator/catalog_handler.go
  v2/internal/pkg/operator/catalog_handler_test.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#1048 CLID-306: upgrades dependencies
  go.mod
  go.sum
  go.work.sum
  v2/go.mod
  v2/go.sum
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#1053 CLID-306: upgrades dependencies
  go.mod
  go.sum
  go.work.sum
  v2/go.mod
  v2/go.sum
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#1047 CLID-300: Update catalog filtering doc
  v2/docs/operator-filtering-investigation.md
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#1044 [release-4.18] OCPBUGS-48842: CLID-301: add --cache-dir command line option
  v2/docs/delete-functionality.md
  v2/internal/pkg/cli/delete.go
  v2/internal/pkg/cli/delete_test.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/cli/executor_test.go
  v2/internal/pkg/mirror/options.go
Labels: backport-risk-assessed, approved, cherry-pick-approved, qe-approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference
