Repository openshift/oc-mirror, pull requests merged in 2025-04, with the labels that each got.

#1120 OCPBUGS-52471: Fix OOM at filtering catalogs
  go.mod
  go.sum
  go.work.sum
  v2/go.mod
  v2/go.sum
  v2/internal/pkg/imagebuilder/catalog_builder.go
  v2/internal/pkg/imagebuilder/rebuild_catalog.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#1062 OCPBUGS-49880: cli: return distinct error codes depending on failure
  v2/go.mod
  v2/internal/pkg/batch/common.go
  v2/internal/pkg/batch/concurrent_chan_worker.go
  v2/internal/pkg/batch/concurrent_worker.go
  v2/internal/pkg/batch/concurrent_worker_test.go
  v2/internal/pkg/batch/error.go
  v2/internal/pkg/batch/new.go
  v2/internal/pkg/cli/delete.go
  v2/internal/pkg/cli/error.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/cli/executor_test.go
  v2/internal/pkg/delete/delete_images.go
  v2/internal/pkg/errcode/code.go
  v2/internal/pkg/release/local_stored_collector.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#1124 CLID-352: images: add integration tests image
  images/cli/Dockerfile.test
Labels: approved, lgtm, jira/valid-reference

#1128 [release-4.18] OCPBUGS-54727: oc-mirror process gets killed abrutply
  go.work.sum
  v2/go.mod
  v2/go.sum
Labels: backport-risk-assessed, approved, cherry-pick-approved, qe-approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#1086 CLID-321: Add annotations to resources generated by oc-mirror v2
  v2/internal/pkg/api/kubernetes/core/type_configmap.go
  v2/internal/pkg/clusterresources/clusterresources.go
  v2/internal/pkg/clusterresources/clusterresources_test.go
Labels: approved, lgtm, jira/valid-reference

#1108 [release-4.18] OCPBUGS-51217: Fix CVE-2025-27144
  go.mod
  go.sum
  go.work.sum
  v2/go.mod
  v2/go.sum
Labels: backport-risk-assessed, approved, cherry-pick-approved, qe-approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1073 OCPBUGS-50617: oc-mirror does not create signature files
  v2/Makefile
  v2/internal/pkg/cli/delete.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/release/cincinnati.go
  v2/internal/pkg/release/cincinnati_test.go
  v2/internal/pkg/release/local_stored_collector_test.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#1127 OCPBUGS-54653: delete: continue on errors
  v2/internal/pkg/cli/delete.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/delete/delete_images.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#1133 OCPBUGS-54891: Fix mirroring images with tag&digest in charts
  v2/internal/pkg/helm/local_stored_collector.go
  v2/internal/pkg/helm/local_stored_collector_test.go
  v2/tests/helm-data/charts/ingress-nginx-4.12.1.tgz
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
