Repository openshift/oc-mirror, pull requests merged in 2025-08, with the labels that each got.

#1233 OCPBUGS-59913: prevents panic when helm chart is nil
  v2/internal/pkg/helm/local_stored_collector.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#1201 CLID-389: v2: validate access to destination registry
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/cli/executor_test.go
Labels: approved, qe-approved, lgtm, jira/valid-reference

#1234 [release-4.19] OCPBUGS-59760: warn if tmp is `noexec`
  cmd/oc-mirror/main.go
Labels: backport-risk-assessed, approved, lgtm, jira/valid-bug, jira/valid-reference
