Repository openshift/oc-mirror, pull requests merged in 2025-07, with the labels that each got.

#1185 OCPBUGS-52470: Fixes the tag when rebuilt catalog by digest only
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/operator/common.go
  v2/internal/pkg/operator/filtered_collector.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1202 OCPBUGS-57370: v2/defaults Fix rate limiting issues by enabling exponential backoff retries
  v2/internal/pkg/cli/const.go
  v2/internal/pkg/mirror/options.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1197 "NO-JIRA: v2: remove build-machinery-go as a go.mod dependency"
  v2/Makefile
  v2/go.mod
  v2/go.sum
Labels: approved, lgtm, jira/valid-reference

#1200 OCPBUGS-58193: v2/archive: error d2m when no tar files found
  v2/internal/pkg/archive/unarchive.go
  v2/internal/pkg/archive/unarchive_test.go
  v2/internal/pkg/cli/executor.go
  v2/internal/pkg/cli/executor_test.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#1213 OCPBUGS-58956: bump helm for CVE fix
  go.mod
  go.sum
  pkg/cli/mirror/operator.go
  pkg/cli/mirror/sequence.go
  v2/go.mod
  v2/go.sum
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#1212 OCPBUGS-59235: [release-4.18] v2/archive: error d2m when no tar files found
  v2/internal/pkg/archive/unarchive.go
  v2/internal/pkg/archive/unarchive_test.go
  v2/internal/pkg/cli/executor_test.go
Labels: backport-risk-assessed, approved, cherry-pick-approved, lgtm, jira/valid-bug, jira/valid-reference

#1214 OCPBUGS-54622: cli/delete: fix workflow mode name output
  v2/internal/pkg/cli/delete.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1226 NO-JIRA: adds build-machinery-go as a tool dependency
  v2/Makefile
  v2/go.mod
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#1228 OCPBUGS-59646: revert #1220 and print a warning instead
  cmd/oc-mirror/main.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
