Repository openshift/oc-mirror, pull requests merged in 2025-06, with the labels that each got.

#1170 [release-4.19] OCPBUGS-55701: v2/imgbuilder: use --authfile when set
  v2/go.mod
  v2/internal/pkg/imagebuilder/builder.go
Labels: backport-risk-assessed, approved, cherry-pick-approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#1162 OCPBUGS-55076: adds code to handle signature errors in the archive pkg
  v2/internal/pkg/archive/archive.go
  v2/internal/pkg/archive/archive_test.go
  v2/internal/pkg/archive/error.go
  v2/internal/pkg/archive/image-blob-gatherer.go
  v2/internal/pkg/archive/image-blob-gatherer_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1179 OCPBUGS-57387: v2/archive: fix sanitization of `.`
  v2/internal/pkg/archive/unarchive.go
  v2/internal/pkg/archive/unarchive_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#1184 OCPBUGS-57461,OCPBUGS-56718: v2/operator: add rebuilt catalog to tar file
  v2/internal/pkg/operator/filtered_collector.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#1172 OCPBUGS-54473: Bug fix - incomplete error messages for helm charts
  v2/internal/pkg/helm/local_stored_collector.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#1173 OCPBUGS-57068: [release-4.18]: v2/imgbuilder: use --authfile when set
  go.work.sum
  v2/go.mod
  v2/internal/pkg/imagebuilder/builder.go
Labels: backport-risk-assessed, approved, cherry-pick-approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#1186 OCPBUGS-55374: Add console warning if bad umask is detected
  v2/internal/pkg/cli/executor.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1181 OCPBUGS-58186: v2/mirror: retry in case of ContextDeadlineExceeded
  v2/internal/pkg/mirror/mirror.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1191 CLID-396: adds README.md for oc-mirror v2
  README.md
  README_v1.md
  v2/README.md
  v2/docs/dev-investigations/OCPSTRAT-1515.md
  v2/docs/dev-investigations/operator-filtering-investigation.md
  v2/docs/dev-investigations/progress-bar-and-concurrencty-investigation.md
  v2/docs/features/delete-functionality.md
  v2/docs/features/enclave_support.md
  v2/docs/features/signature-verification.md
  v2/docs/image-set-examples/image-set-config.yaml
Labels: approved, lgtm, jira/valid-reference
